<?php if ($this->pageCount): ?>
<div class="paginationControl pagination">
<!-- Previous page link -->
<?php if (isset($this->previous)): ?>
  <a href='/platos/index/verplatos?id=<?php echo $this->variable;?>&page=<?php echo $this->previous?>'>
      
    « 
  </a> |
<?php else: ?>
  <span class="disabled">«</span> |
<?php endif; ?>

<!-- Numbered page links -->
<?php foreach ($this->pagesInRange as $page): ?>
  <?php if ($page != $this->current): ?>
    <a href='/platos/index/verplatos?id=<?php echo $this->variable;?>&page=<?php echo $page; ?>'>
        <?php echo $page; ?>
    </a> |
  <?php else: ?>
    <?php echo $page; ?> |
  <?php endif; ?>
<?php endforeach; ?>

<!-- Next page link -->
<?php if (isset($this->next)): ?>
  <a href='/platos/index/verplatos?id=<?php echo $this->variable;?>&page=<?php echo $this->next?>'>
    »
  </a>
<?php else: ?>
  <span class="disabled">»</span>
<?php endif; ?>
</div>
<?php endif; ?>