   <div class="content-left">
   		<div class="descrip-product">
   			<div class="etiqueta-cat">
   				<div class="etiqueta">
   					<p>Destacados - <span>Ceviche</span></p>
   				</div>
   			</div>
   			<div class="ficha-product">
   				<div class="ficha-img">
   					<img src="/img/ceviche.jpg">
   				</div>
   				<div class="ficha-desc">
                  <h2><?php echo $this->lista[0]['restaurant_nombre'];?></h2>
   					<div class="puntuaciones c<?php echo $this->lista[0]['ta_puntaje_in_id'];?>"></div>
                  <h3><?php echo $this->lista[0]['va_nombre'];?></h3>
   					<p class="desc"><?php echo $this->lista[0]['tx_descripcion'];?></p>
   					<p class="costo">Costo</p>
   					<p class="precio"><?php echo $this->lista[0]['va_precio'];?></p>
   				</div>
   			</div>
   			<div class="content-coments">
   				<div class="coments-all">
   					<div class="top-coment">
   						<p>7 comentarios realizados</p>
   						<a href="#" class="btn btn-warning agregar-coment-1">Agregar comentario</a>
   					</div>
   					<div class="agregar-comentario-desc" style="display:none;height:376px;">
   						<?php
							$title = 'Agregar nuevo comentario';
							$this->headTitle($title);
							?>
							<div class="form-envio-men">

							<?php
							$form = $this->form;
							//$form->setAttribute('action', $this->url('usuario', array('action' => 'add')));
							$form->setAttributes(array(
							    'action' => $this->url.'/platos/index/verplatos?id='.$this->lista[0]['in_id'],//'/usuario/comentarios/agregarcomentarios',
							    'method' => 'post',
							    'class' => 'form-horizontal'
							));
							$form->prepare();


							echo $this->form()->openTag($form);
							?><legend><?php echo $this->escapeHtml($title); ?></legend>
							<?php
							echo $this->formHidden($form->get('in_id'));   
							echo $this->formHidden($form->get('Ta_puntaje_in_id'));
							echo $this->formHidden($form->get('Ta_plato_in_id'));
							?>
							<div class="control-group"><?php echo $this->formRow($form->get('va_nombre'));?></div>
							<div class="control-group"><?php echo $this->formRow($form->get('va_email'));?></div>
							<div class="control-group"><p id="star"></p> </div>
							<div class="control-group"><?php echo $this->formRow($form->get('tx_descripcion'));?></div>
							<div class="control-group"><?php echo $this->formSubmit($form->get('submit'));?></div>


							 <?php echo $this->form()->closeTag(); ?>
						</div>
   					</div>
   					<div class="comentarios-one">
   						<ul>
                        <?php  foreach ($this->comentarios  as $comt) : ?>
	   							<li>
	   								<div class="coment-li">
	   									<div class="img-li">
	   										<img src="/img/foto-carnet.jpg">
	   									</div>
	   									<div class="img-li-desc">
	   										<div class="img-li-top">
                                       <h4><?php echo $comt->va_nombre_cliente?></h3>
	   											<div class="puntuaciones c<?php echo $comt->ta_puntaje_in_id;?>"></div>
	   										</div>
	   										<div class="img-li-bottom">
	   											<p> <?php echo $comt->tx_descripcion?></p> 
	   										</div>
	   									</div>
	   								</div>
	   							</li>
                                                                <?php endforeach;?>
                                                                

   						</ul>
   					</div>
   				</div>
   				<div class="content-info">
   					<div class="info-img">
   						<img src="/img/default-img.jpg">
   					</div>
   					<h4>Ubicación de local</h4>
   					<ul class="ubi-lupa">
   						<li>
   							<div class="ubicancion"><?php echo $this->lista[0]['va_direccion'];?>-<?php echo $this->lista[0]['distrito'];?></div>

<!--                                                                <div class="ubicancion">Av. Javier Prado Este N° 1860. - San Borja</div>-->
   						</li>
   						<li>
   							<div class="lupa"><a href="#">Ver mapa</a></div>
   						</li>
   					</ul>
   					<h4>Atención</h4>
   					<ul class="time">
   						<li><span class="day"><?php echo $this->lista[0]['va_dia'];?></span></li>
   						<li><span class="hour"><?php echo $this->lista[0]['va_horario'];?></span></li>
   					</ul>
   				</div>
   			</div>
   			
   		</div>
   </div>
<script type="text/javascript">
	$(document).ready(function(){
		$(".agregar-coment-1").click(function(e){
			e.preventDefault();
			if ($(".agregar-comentario-desc").is(":hidden")) {
		      $(".agregar-comentario-desc").show("slow");
		    } else {
		      $(".agregar-comentario-desc").slideUp();
		    }
		});
	});
</script>
