<link rel="stylesheet" href="<?php echo $this->basePath()?>/css/jquery-ui.css">
   <div class="content-left">
      <?php
      $formu = $this->formu;
      //$form->setAttribute('action', $this->url('usuario', array('action' => 'add')));

      $formu->setAttributes(array(
          'action' => $this->url.'/buscar-por-distrito',
          'method' => 'get'
      ));
      $formu->prepare();

      echo $this->form()->openTag($formu);
      ?>
      <?php
      echo $this->formHidden($formu->get('in_id'));
      ?><?php echo $this->formRow($formu->get('distrito'));?><?php
      ?><?php echo $this->formRow($formu->get('q'));?><?php


      ?><?php echo $this->formSubmit($formu->get('submit'));?><?php
      ?><a style="margin-left: 10px;" class="disabled" id="buscarmap" disabled>Ver Mapa </a><?php
      echo $this->form()->closeTag(); ?>
      <div id="esconder">
   		<div class="descrip-product">
   			<div class="etiqueta-cat">
   				<div class="etiqueta">
   					<p><span><?php echo $this->lista[0]['tipo_plato_nombre'];?></span></p>
   				</div>
           <div class="return">
              <a href="javascript:window.history.back();">Regresar</a>
           </div>
   			</div>
   			<div class="ficha-product">
   				<div class="ficha-img">
   					<img src="<?php echo $this->host('images') . '/' . $this->lista[0]['va_imagen'];?>">
   				</div>
   				<div class="ficha-desc">
                  <h2><?php echo $this->lista[0]['restaurant_nombre'];?></h2>  
   					<div class="puntuaciones c<?php echo $this->lista[0]['Ta_puntaje_in_id'];?>"></div>
                  <h3><?php echo $this->lista[0]['va_nombre'];?></h3>
   					<p class="desc"><?php echo $this->lista[0]['tx_descripcion'];?></p>
   					<p class="costo">Costo</p>
   					<p class="precio">S/.<?php echo $this->lista[0]['va_precio'];?></p>
   				</div>
   			</div>
   			<div class="content-coments">
   				<div class="coments-all">
                  <div class="cont-accesorios">
                     <div class="left-desc">

                        <h4>Dirección</h4>
                        <ul class="ubi-lupa">

                           <li>
                            <div class="ubicancion"><?php echo $this->lista[0]['va_direccion'];?>-<?php echo $this->lista[0]['distrito'];?></div>
                           </li>

                        </ul>
                        <h4>Teléfono</h4>
                        <ul class="servicios-desc">
                            <li><?php echo $this->lista[0]['va_telefono'];?></li>
                        </ul>
                        <h4>Atención</h4>
                        <ul class="time">
                            <li><span class="day"><?php echo $this->lista[0]['va_dia']; ?></span></li>
                            <li><span class="hour"><?php echo $this->lista[0]['va_horario']; ?></span></li>
                        </ul>
                    </div>
                    <div class="right-desc">
                        <h4>Medios de pago</h4>
                        <ul class="servicios-desc">
                            <?php foreach ($this->pagos as $pago): ?>
                                <li><?php echo $pago->nom_pago; ?></li>
                            <?php endforeach;?>
                        </ul>
                        <h4>Servicio</h4>
                        <ul class="servicios-desc">
                            <?php foreach ($this->servicios as $serv): ?>
                                <li><?php echo $serv->nom_servicio; ?></li>
                            <?php endforeach; ?>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="content-info">
                <div class="info-img">
                    <img src="<?php echo $this->host('images') . '/' . $this->lista[0]['restaurant_img']; ?>">
                </div>
                <h4 class="ubi-map">Ubicación <span></span></h4>
                <div id="mapCont" class="map" data-lat="<?php echo $this->lista[0]['de_latitud']; ?>" data-lng="<?php echo $this->lista[0]['de_longitud']; ?>"></div>
                <h4>Sucursales</h4>
                <section class="list-suc">
                    <ul class="ul-suc">
                        <?php foreach ($this->locales as $local) : ?>
                            <li class="li-suc"> 
                                <a href="#" class="" data-lat="<?php echo $local->de_latitud ?>" data-lng="<?php echo $local->de_longitud ?>">
                                    <header>                              
                                        <h6 class="text-ellipsis"><?php echo $this->lista[0]['restaurant_nombre'];?></h6>
                                        <span class="close-banch"></span>
                                    </header>
                                    <div class="descr">
                                        <span class="house-icon"></span>
                                        <ul>
                                            <li class="text-ellipsis"><?php echo $local->va_direccion ?></li>
                                            <li class="phone"><span class="text-ellipsis"><?php echo $local->distrito ?></span><em class="text-ellipsis"><?php echo $local->va_telefono ?></em></li>
                                        </ul>
                                    </div>
                                </a>                                       
                            </li>
                        <?php endforeach; ?>

                    </ul>
                </section>

            </div>
            <div class="coments-all coments-all-fin">
              <!--Comentarios-->
              <div class="top-coment">
                  <p><?php echo $this->lista[0]['num']; //$this->cantidad; ?> comentarios</p>
                  <a href="#" class="btn btn-warning agregar-coment-1">Agregar comentario</a>
              </div>
              <div class="agregar-comentario-desc" style="display:none;">
                  <?php
                  $title = 'Agregar nuevo comentario';
                  $this->headTitle($title);
                  ?>
                  <div class="form-envio-men">
                      <?php
                      $form = $this->form;
                      //$form->setAttribute('action', $this->url('usuario', array('action' => 'add')));
                      $form->setAttributes(array(
                          'action' => $this->url . '/platos/index/verplatos?id=' . $this->lista[0]['in_id'], //'/usuario/comentarios/agregarcomentarios',
                          'method' => 'post',
                          'class' => 'form-horizontal'
                      ));
                      $form->prepare();

                      echo $this->form()->openTag($form);
                      ?><legend><?php echo $this->escapeHtml($title); ?></legend>
                      <?php
                      echo $this->formHidden($form->get('in_id'));
                      echo $this->formHidden($form->get('Ta_puntaje_in_id'));
                      echo $this->formHidden($form->get('Ta_plato_in_id'));
                      ?>
                      <div class="control-group"><?php echo $this->formRow($form->get('va_nombre')); ?></div>
                      <div class="control-group"><?php echo $this->formRow($form->get('va_email')); ?></div>
                      <div class="control-group">
                        <label>Valora tu plato:</label>
                        <p id="star"></p> 
                      </div>
                      <div class="control-group"><?php echo $this->formRow($form->get('tx_descripcion'));?></div>
                      <div class="control-group"><?php echo $this->formSubmit($form->get('submit')); ?></div>
                      <?php echo $this->form()->closeTag(); ?>
                  </div>
              </div>
              <div class="comentarios-one">
                  <ul>

                      <?php
                      if ($this->lista[0]['Ta_puntaje_in_id'] != 0) {
                          foreach ($this->comentarios as $comt) :
                              ?>

                              <li>
                                  <div class="coment-li">
                                      <div class="img-li">
                                          <img src="/img/foto-carnet.jpg">
                                      </div>
                                      <div class="img-li-desc">
                                          <div class="img-li-top">
                                              <h4><?php  
                                              if(strlen($comt->va_nombre_cliente)>15){
                                              $str=trim(substr($comt->va_nombre_cliente, 0, 15));
                                              $str.='...';
                                              }else {$str=$comt->va_nombre_cliente;} 
                                              echo $str;
                                               ?></h3>
                                                  <div class="puntuaciones c<?php echo $comt->ta_puntaje_in_id; ?>"></div>
                                          </div>
                                          <div class="img-li-bottom">
                                              <p> <?php echo $comt->tx_descripcion ?></p> 
                                          </div>
                                      </div>
                                  </div>
                              </li>
                              <?php
                          endforeach;
                      }
                      ?>
                  </ul>
                  <?php echo (count($this->comentarios)> 10)?$this->paginationControl($this->comentarios, 'Sliding', 'platos/index/paginador.phtml',array('variable'=>'/platos/index/verplatos?id='.$this->variable.'&')):""; ?>
              </div>
              <!--Fin de comentarios-->
            </div>
        </div>

    </div>
</div>
       <div id="mapa-buscador">
<!--        <div id='map' style="height:800px;"></div>-->
 </div>
</div>
<script src="<?php echo $this->basePath()?>/js/jquery-ui.js"></script>
<!-- <script src="https://maps.googleapis.com/maps/api/js?sensor=true"></script>    -->     
<script src="<?php echo $this->basePath()?>/js/vendor/gmaps.js"></script>
<script src="<?php echo $this->basePath()?>/js/vendor/jquery.validate.js"></script>
<script src="<?php echo $this->basePath()?>/js/vendor/jquery.raty.min.js"></script>
<script src="<?php echo $this->basePath()?>/js/verplatos.min.js"></script>

		
