<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'SanAuth2\Module'                       => __DIR__ . '/Module.php',
    'SanAuth2\Controller\AuthController'    => __DIR__ . '/src/SanAuth2/Controller/AuthController.php',
    'SanAuth2\Controller\SuccessController' => __DIR__ . '/src/SanAuth2/Controller/SuccessController.php',
    'SanAuth2\Model\MyAuthStorage'          => __DIR__ . '/src/SanAuth2/Model/MyAuthStorage.php',
//    'SanAuth\Model\User'                   => __DIR__ . '/src/SanAuth/Model/User.php',
);