<?php


$title = 'Agregar nuevo usuario';
$this->headTitle($title);
?>


<?php
$form = $this->form;
//$form->setAttribute('action', $this->url('usuario', array('action' => 'add')));

$form->setAttributes(array(
    'action' => $this->url.'/usuario/index/agregarusuario',
    'method' => 'post'
));
$form->prepare();

echo $this->form()->openTag($form);
?><div class="modal-header">
<a id="cerrar_update_usuario" class="close">×</a>
<h3><?php echo $this->escapeHtml($title); ?></h3>
</div><?php
echo $this->formHidden($form->get('in_id'));


?><div class="span8"><?php
?><div class="control-group "><?php echo $this->formRow($form->get('va_nombre'));?><div class="control-group "><?php
?><div class="control-group "><?php echo $this->formRow($form->get('va_apellidos'));?><div class="control-group "><?php
?><div class="control-group "><?php echo $this->formRow($form->get('va_email'));?><div class="control-group "><?php
?><div class="control-group "><?php echo $this->formRow($form->get('va_contrasenia'));?><div class="control-group "><?php
?><div class="control-group "><?php echo $this->formRow($form->get('va_contrasenia2'));?><div class="control-group "><?php
?><div class="control-group "><?php echo $this->formRow($form->get('Ta_rol_in_id'));?><div class="control-group "><?php
?><div class="control-group "><?php echo $this->formSubmit($form->get('submit'));?><div class="control-group "><?php
?><div class="span10"><?php
echo $this->form()->closeTag(); 