 
<form name='form_busqueda' action='<?php echo $this->basePath();?>/usuario/index/listar' method ="post">
	<input type='text' name='texto'/>
<input type='radio' name='listado'  id='nom' value='va_nombre' />Por nombre
<!--<input type='radio' name='listado' id='dire' value='direccion'/>Por direccion checked-->

<input type='radio' name='listado' id='dire1' value='1'/>Por Administrador
<input type='radio' name='listado' id='dire2' value='2'/>Por Editor

<input name=submit type='submit'/>
<p>JSON</p>
<a href='http://192.168.1.35:8080/usuario/index/jsonlistar'>Ver listado con Json</a>

<table class="table table-bordered table-hover">
    <thead>  
<tr>
    <th>#</th> 
    <th>N°</th>
    <th>Status</th>
    <th>Nombre</th>
    <th>Apellidos</th>
    <th>Email</th>
    <th>Rol</th>
    <th>Operaciones;</th>
</tr>
</thead>
<?php $count=1; 
foreach ($usuarios as $usuario) : ?>
<tr id="<?php echo $this->escapeHtml($usuario->in_id);?>">
    <td><input id="<?php echo $this->escapeHtml($usuario->in_id);?>" type="checkbox" class="check"> </td>
    <td><?php echo $count++?></td>
    <td><span id="la<?php echo $this->escapeHtml($usuario->in_id);?>" class='label label-success'> <?php echo $this->escapeHtml($usuario->en_estado);?></span></td>
    <td><?php echo $this->escapeHtml($usuario->va_nombre);?></td> 
    <td><?php echo $this->escapeHtml($usuario->va_apellidos);?></td>
    <td><?php echo $this->escapeHtml($usuario->va_email);?></td>
    <td><?php echo $this->escapeHtml($usuario->va_nombre_rol);?></td>
<!--    <td><a href="/usuario/index/obtonerjoin?id=<?php echo $usuario->in_id?>" class='modificar btn btn-info'><i class='icon-edit icon-white'></i>Editar</a></td>
    <td><a href="/usuario/index/eliminarusu?id=<?php echo $usuario->in_id?>" class='eli btn btn-danger'><i class='icon-trash icon-white'></i>ELIMINAR</a> </td>-->
    <td><a data-id="<?php echo $this->escapeHtml($usuario->in_id);?>" href="<?php echo $this->basePath();?>/usuario/index/editarusuario/<?php echo $usuario->in_id;?>" class='modificar btn btn-info'><i class='icon-edit icon-white'></i>Editar</a></td>
    <td><a data-id="<?php echo $this->escapeHtml($usuario->in_id);?>" href="#" class='eli btn btn-danger'><i class='icon-trash icon-white'></i>ELIMINAR</a> </td>
<!--    <td><a href="/usuario/index/cambiaestado?id=<?php echo $usuario->in_id?>&estado=activo">ACTIVAR</a> </td>
    <td><a href="/usuario/index/cambiaestado?id=<?php echo $usuario->in_id?>&estado=desactivo">DESACTIVAR</a> </td>-->
</tr>
<?php endforeach; ?>
</table>

