
<strong>Module:</strong>        ZendSkeletonModule &raquo;
<strong>Controller:</strong>    Skeleton &raquo;
<strong>Action:</strong>        foo
<table class="table">
<tr>
    <th>Nombre</th>
    <th>Direccion</th>
    <th>&nbsp;</th>
    <th><?php echo $this->data;?></th>
</tr>
<?php foreach ($lista as $usuario) : ?>
<tr>
    <td><?php echo $this->escapeHtml($usuario->nombre);?></td>
    <td><?php echo $this->escapeHtml($usuario->direccion);?></td>
</tr>
<?php endforeach; ?>
</table>

