<?php
$title = 'Agregar nuevo comentario';
$this->headTitle($title);
?>
<div class="span8">

<?php
$form = $this->form;
//$form->setAttribute('action', $this->url('usuario', array('action' => 'add')));
$form->setAttributes(array(
    'action' => $this->url.'/usuario/clientes/agregarcomentarios',
    'method' => 'post'
));
$form->prepare();


echo $this->form()->openTag($form);
?><legend><?php echo $this->escapeHtml($title); ?></legend>
<?php
echo $this->formHidden($form->get('in_id'));   
echo $this->formHidden($form->get('Ta_puntaje_in_id'));
echo $this->formHidden($form->get('Ta_plato_in_id'));
?>
<div class="control-group span5 "><?php echo $this->formRow($form->get('va_nombre'));?></div>
<div class="control-group span5"><?php echo $this->formRow($form->get('va_email'));?></div>
<div class="control-group span5"><?php echo $this->formRow($form->get('tx_descripcion'));?></div>
<div class="control-group span12"><?php echo $this->formSubmit($form->get('submit'));?></div>

 <?php echo $this->form()->closeTag(); ?>
</div>