  <!--   <div class="span2">
    <div class="btn-group" data-toggle="buttons-radio">
  <a  class="btn" href="<?php echo $this->basePath();?>/restaurante/index/agregarrestaurante">AGREGAR RESTAURANTE</a>
    </div>
    </div> -->
    <div class="span10">
     <div class="input-append"> 
<form name='form_busqueda'class="form-search" action='<?php echo $this->basePath(); ?>/restaurante' method ="post">
   <div class="control-group">

   </label>
   <label class="ra radio">    
   POR ESTADO :
   <SELECT NAME="estado" SIZE="1">
   <OPTION VALUE="">seleccione:</OPTION>
   <OPTION VALUE="activo">activo</OPTION>
   <OPTION VALUE="desactivo">desactivo</OPTION>
   </SELECT>
   </label>
    <label class="ra radio">POR NOMBRE DE PLATO:
    <input type='text' name='texto' id="texto"/>
    <input type="submit" class="btn" name="submit" value="Buscar">
    </div>
    </div>
    </form>
    </div>    

<div class="span10" id="flip-scroll">
<table class="table table-bordered table-hover">
    <thead class="cf">  
    <thead>  
        <tr>
            <th>#</th> 
            <th>N°</th>
            <th>Status</th>
            <th>Comentario</th>
            <th>Puntaje</th>
            <th>Plato</th>
            <th>Usuario</th>
            <th>Operaciones</th>
        </tr>
    </thead>

    <?php $count = 1;
    foreach ($this->comentarios as $cometarios) :
        ?>
        <tr>
            <td><?php echo $count++ ?></td>
    <?php if ($cometarios->en_estado == 'aprobado') { ?>
                <td><input id="<?php echo $this->escapeHtml($cometarios->in_id); ?>" type="checkbox" class="check" checked="checked"> </td>
                <td><span id="la<?php echo $this->escapeHtml($cometarios->in_id); ?>" class='label label-success'> <?php echo $this->escapeHtml($cometarios->en_estado); ?></span></td>
    <?php } else { ?>
                <td><input id="<?php echo $this->escapeHtml($cometarios->in_id); ?>" type="checkbox" class="check"> </td>
                <td><span id="la<?php echo $this->escapeHtml($cometarios->in_id); ?>" class='label label-important'> <?php echo $this->escapeHtml($cometarios->en_estado); ?></span></td>
    <?php } ?>
            <td><?php echo $this->escapeHtml($cometarios->tx_descripcion); ?></td> 
            <td><?php echo $this->escapeHtml($cometarios->va_valor); ?></td>
            <td><?php echo $this->escapeHtml($cometarios->va_nombre); ?></td>
            <td><?php echo $this->escapeHtml($cometarios->va_nombre_cliente); ?></td>
         <td><a name="<?php echo $this->escapeHtml($cometarios->tx_descripcion); ?>" data-id="<?php echo $this->escapeHtml($cometarios->in_id); ?>" href="#" class='eli btn btn-danger'><i class='icon-trash icon-white'></i>ELIMINAR</a> </td>
        </tr>

<?php endforeach; ?>
<!--        <div style="clear: both;">
<?php (count($this->paginator)> 0)?$this->paginationControl($this->paginator, 'Sliding', 'usuario/index/paginador.phtml'):""; ?>