<?php


$title = 'Agregar nuevo restaurante';
$this->headTitle($title);
?>


<?php
$form = $this->form;
//$form->setAttribute('action', $this->url('usuario', array('action' => 'add')));

$form->setAttributes(array(
    'action' => $this->url.'/restaurante/index/agregarrestaurante',
    'method' => 'post'
));

?><div class=""><?php
$form->prepare();

echo $this->form()->openTag($form);
?><h3><?php echo $this->escapeHtml($title); ?></h3>
<?php
echo $this->formHidden($form->get('in_id'));
?><div class="control-group "><?php echo $this->formRow($form->get('va_nombre'));?></div><?php
?><div class="control-group "><?php echo $this->formRow($form->get('va_razon_social'));?></div ><?php
?><div class="control-group "><?php echo $this->formRow($form->get('va_web'));?></div><?php
?><div class="control-group "><?php echo $this->formRow($form->get('va_imagen'));?></div><?php
?><div class="control-group "><?php echo $this->formRow($form->get('va_ruc'));?></div><?php
?><div class="control-group "><?php echo $this->formRow($form->get('Ta_tipo_comida_in_id'));?></div><?php
?><div class="control-group "><?php echo $this->formRow($form->get('va_modalidad'));?></div><?php
?>
<div id="modalidad"></div>
<div class="control-group "><?php echo $this->formSubmit($form->get('submit'));?></div><?php
echo $this->form()->closeTag();?> </div>



