<?php


$title = 'EDITAR RESTAURANTE '.$this->va_nombre;
$this->headTitle($title);
?>
<div class="span8">
<?php
$form = $this->form;
//$form->setAttribute('action', $this->url('usuario', array('action' => 'add')));
$form->setAttributes(array(
    'action' => $this->url.'/restaurante/index/editarrestaurante/'.$this->in_id.'/'.$this->va_nombre,
    'method' => 'post',
    'in_id'   =>$this->in_id,
));
$form->prepare();


echo $this->form()->openTag($form);

?><h3><?php echo $this->escapeHtml($title); ?></h3>
<?php
echo $this->formHidden($form->get('in_id'));
?><div class="control-group "><?php echo $this->formRow($form->get('va_nombre'));?></div><?php
?><div class="control-group "><?php echo $this->formRow($form->get('va_razon_social'));?></div ><?php
?><div class="control-group "><?php echo $this->formRow($form->get('va_web'));?></div><?php
?><div class="control-group "><?php echo $this->formRow($form->get('va_imagen'));?></div><?php
?><div class="control-group "><?php echo $this->formRow($form->get('va_ruc'));?></div><?php
?><div class="control-group "><?php echo $this->formRow($form->get('Ta_tipo_comida_in_id'));?></div><?php
?><div class="control-group ">medio de pago</div><?php
?><div class="control-group "><?php echo $this->formRow($form->get('va_modalidad'));?></div><?php
?><div class="control-group "><?php echo $this->formSubmit($form->get('submit'));?></div><?php
echo $this->form()->closeTag();?> 
</div>
<script>
	$(document).ready(function(){
		var id=$('#in_id').val();
		var url="/restaurante/index/medi?in_id=" + id
		$.getJSON(url,function(data){ 
             
            $.each(data,function(i,val){
            $(".checkbox").each(function(){ 
              var va = $(this).attr('value');
              console.log(val.Ta_medio_pago_in_id);
    	     if (va==val.Ta_medio_pago_in_id ){
                $(this).prop("checked" , true ); 
             } 
             });                       
    });
});
	});
</script>
