<?php


$title = 'EDITAR RESTAURANTE '.$this->va_nombre;
$this->headTitle($title);
?>
<?php
$form = $this->form;
//$form->setAttribute('action', $this->url('usuario', array('action' => 'add')));
$form->setAttributes(array(
    'action' => $this->url.'/restaurante/index/editarrestaurante/'.$this->in_id.'/'.$this->va_nombre,
    'method' => 'post',
    'in_id'   =>$this->in_id,
));
$form->prepare();


echo $this->form()->openTag($form);
?><h3><?php echo $this->escapeHtml($title); ?></h3>
<?php
echo $this->formHidden($form->get('in_id'));
?><div class="control-group "><?php echo $this->formRow($form->get('va_nombre'));?></div><?php
?><div class="control-group "><?php echo $this->formRow($form->get('va_razon_social'));?></div ><?php
?><div class="control-group "><?php echo $this->formRow($form->get('va_web'));?></div><?php
?><div class="control-group "><?php echo $this->formRow($form->get('va_imagen'));?></div><?php
?><div class="control-group "><?php echo $this->formRow($form->get('va_ruc'));?></div><?php
?><div class="control-group "><?php echo $this->formRow($form->get('Ta_tipo_comida_in_id'));?></div><?php
?>
<div id="modalidad">
  <label>Modalidad de Pago</label>
  <label class='checkbox inline' id="comodal">
</div>
<div class="control-group "><?php echo $this->formSubmit($form->get('submit'));?></div><?php
echo $this->form()->closeTag();?> </div>

