    <div class="span2">
    <div class="btn-group" data-toggle="buttons-radio">
  <a  class="btn" href="<?php echo $this->basePath();?>/restaurante/index/agregarrestaurante">AGREGAR RESTAURANTE</a>
    </div>
    </div>
    <div class="span4">
     <div class="input-append"> 
<form name='form_busqueda'class="form-search" action='<?php echo $this->basePath(); ?>/restaurante' method ="post">
   <div class="control-group">
   <label class="ra radio">    
   POR TIPO :
   <SELECT NAME="comida" SIZE="1">
   <OPTION VALUE="">seleccione:</OPTION>
 <?php  foreach ($this->comida as $comida) : ?>
 <OPTION VALUE="<?php echo $comida['in_id']; ?>"><?php echo $comida['va_nombre_tipo']; ?></OPTION>
<?php endforeach; ?>
   </SELECT>
   </label>
   <label class="ra radio">    
   POR ESTADO :
   <SELECT NAME="estado" SIZE="1">
   <OPTION VALUE="">seleccione:</OPTION>
   <OPTION VALUE="activo">activo</OPTION>
   <OPTION VALUE="desactivo">desactivo</OPTION>
   </SELECT>
   </label>
    <label class="ra radio">POR NOMBRE:
    <input type='text' name='texto' id="texto"/>
    <input type="submit" class="btn" name="submit" value="Buscar">
    </div>
    </div>
    </form>
    </div>    

<div class="span10">
<table class="table table-bordered table-hover">
    <thead>  

        <tr>
          <th>#</th> 
            <th>N°</th>
            <th>Status</th>
            <th>Nombre</th>
            <th>Razon Social</th>
            <th>Web</th>
            <th>Especialidad</th>
            <th>Operaciones</th>
        </tr>
    </thead>
 

    <?php $count = 1;
    foreach ($this->restaurante  as $usuario) :// foreach ($this->paginator as $usuario) :
        ?>
        <tr>
            <td><?php echo $count++ ?></td>
    <?php if ($usuario->en_estado == 'activo') { ?>
                <td><input id="<?php echo $this->escapeHtml($usuario->in_id); ?>" type="checkbox" class="check_rest" checked="checked"> </td>
                <td><span id="la<?php echo $this->escapeHtml($usuario->in_id); ?>" class='label label-success'> <?php echo $this->escapeHtml($usuario->en_estado); ?></span></td>
    <?php } else { ?>
                <td><input id="<?php echo $this->escapeHtml($usuario->in_id); ?>" type="checkbox" class="check_rest"> </td>
                <td><span id="la<?php echo $this->escapeHtml($usuario->in_id); ?>" class='label label-important'> <?php echo $this->escapeHtml($usuario->en_estado); ?></span></td>
    <?php } ?>
            <td><a href="<?php echo $this->basePath();?>/local/index/index/<?php echo $usuario->in_id;?>"><?php echo $this->escapeHtml($usuario->va_nombre); ?></a></td> 
            <td><?php echo $this->escapeHtml($usuario->va_razon_social); ?></td>
            <td><?php echo $this->escapeHtml($usuario->va_web); ?></td>
            <td><?php echo $this->escapeHtml($usuario->va_nombre_tipo); ?></td>
            <td><a data-id="<?php echo $this->escapeHtml($usuario->in_id); ?>" href="<?php echo $this->basePath();?>/restaurante/index/editarrestaurante/<?php echo $usuario->in_id;?>/<?php echo $usuario->va_nombre;?>" class='modificar btn btn-info'><i class='icon-edit icon-white'></i>Editar</a></td>
           <td><a name="<?php echo $this->escapeHtml($usuario->va_nombre); ?>" data-id="<?php echo $this->escapeHtml($usuario->in_id); ?>" href="/local/index/agregarlocal?id=<?php echo $usuario->in_id;?>" class='listar btn btn-primary'><i class='icon-tasks icon-white'></i>LOCAL</a> </td>
        </tr>

<?php endforeach; ?>
<!--        <div style="clear: both;">
<?php (count($this->paginator)> 0)?$this->paginationControl($this->paginator, 'Sliding', 'usuario/index/paginador.phtml'):""; ?>
</div>-->
<!--  ------------------------PAGINADOR------------------------------------------------>
  


<!-- -------------------------fin---------------------------------------->


</table>

</div>


