<?php echo $this->doctype(); ?>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <title>Lista del Sabor</title>
  <meta name="description" content="ListaDelSabor.com es una lista de los platos más buscados y mejor recomendados en el Perú, en ella ubicarás sus datos, los restaurantes que lo venden y su valoración por los comensales">
  <meta name="viewport" content="width=device-width">
  <link href="<?php echo $this->host('static')?>/img/favicon.ico" rel="shortcut icon" type="image/x-icon"/>
  <script type="text/javascript" src="<?php echo $this->host('static') ?>/js/modernizr.js"></script>           
  <script src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false"></script>         

    <script src="<?php echo $this->basePath()?>/js/lib/jquery-1.8.3.min.js"></script>  

  <?php echo $this->headLink()->prependStylesheet($this->basePath() . '/css/estilos.css')
                  ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

        <!--<script type="text/javascript">
          function initialize() {
            var centerLng = new google.maps.LatLng(-12.111858,-77.016091);
            var styles = [
              {
                stylers: [
                  { hue: "#00ffe6" },
                  { saturation: -20 }
                ]
              },{
                featureType: "road",
                elementType: "geometry",
                stylers: [
                  { lightness: 100 },
                  { visibility: "simplified" }
                ]
              },{
                featureType: "road",
                elementType: "labels",
                stylers: [
                  { visibility: "off" }
                ]
              }
            ];
            var myOptions = {
              zoom: 14,
              center: centerLng,
              scrollwheel: false,
              navigationControl: false,
              mapTypeControl: false,
              scaleControl: false,
              draggable: false,
              streetViewControl: false,
              styles: styles,
              mapTypeId: google.maps.MapTypeId.ROADMAP
            };
            var map = new google.maps.Map(document.getElementById("map_canvas"),
                myOptions);
          }
        </script>-->
    </head>

  <body class="lista-<?php echo $this->clase; ?>">
    <!--<div id="map_canvas" style="position: fixed!important; top: 0; bottom: 0; left: 0; right: 0; z-index: 0;"></div>-->
    <div class="contenido">
      <div class="content-sidebar">
        <div class="contenido-busqueda">
          <div class="content-sidebar-ho">
          <a class="title-home-listado" href="<?php echo $this->basePath(); ?>/" title="Listado del Sabor">
              <h1>
              <img src="<?php echo $this->host('static')?>/img/logo.png" alt="logo">
            </h1>
          </a>
          <span class="logan-1" style="font-size: 3.1em;text-align: right;">-</span> 
          <span class="logan" style="width: 54%;">..y hoy, ¿qué se te antoja?</span> 
          <span class="logan-1" style="font-size: 3.1em;  text-align: right;">-</span>
          <div class="fec"><img src="<?php echo $this->host('static')?>/img/flecha-1.png" alt=""></div>

          
                        <?php     
                        header('Content-Type: text/html; charset=utf-8');
                        $limite = 9;    
                        $resultados = false;
                        
                         $filter   = new \Zend\I18n\Filter\Alnum(true);
                  $texto = $filter->filter($_REQUEST['q']);
                        $palabraBuscar = isset($texto) ? $texto : false;
                          $fd = array (  
                            'fq'=>'en_estado:activo AND restaurant_estado:activo');
                         
                        if ($palabraBuscar)
                        { 
                          require './vendor/SolrPhpClient/Apache/Solr/Service.php';
                         $solar = new Apache_Solr_Service('192.168.1.38', 8983, '/solr/');
                          if (get_magic_quotes_gpc() == 1)
                          {
                            $palabraBuscar = stripslashes($palabraBuscar);
                          }
                          try
                          {
                            $resultados = $solar->search($palabraBuscar, 0, $limite,$fd );
                         

                          }
                          catch (Exception $e)
                          {
                             
                           die("<html><head><title>SEARCH EXCEPTION</title><body><pre>{$e->__toString()}</pre></body></html>");
                          }
                        } ?>          
      
          
            <form  accept-charset="utf-8" method ="get" class="form-horizontal" id="search" action='<?php echo $this->url; ?>/buscar'>
          <input id="q" name="q"  type="text"  value="<?php echo htmlspecialchars($palabraBuscar, ENT_QUOTES, 'utf-8'); ?>" placeholder="Ingrese el plato"  required="required"/>
              <input type="submit"  class="btn btn-search-home" value="Buscar"/>
              <em>Ejm: lomo saltado</em>
            </form>  
          
          
          
   
            <div class="final">
                <img src="<?php echo $this->host('static')?>/img/responsive.png" alt="" style="padding: 37px 10px;">
              </div>
          
              <div class="solicitar-publicacion">
                <a href="/solicita" class="btn btn-warning btn-soli">Solicite su publicación</a>
              </div>
          </div>
          </div><!--Fin del sidebar-->
      </div>

      <div class="contenido-plato">         
        <?php echo $this->content; ?>
       
        <div class="subir">
          <a href="#top"><img src="<?php echo $this->host('static')?>/img/scroll-top.png" alt=""></a>
        </div>
        <!--  <div class="arrow">
            <img src="<?php echo $this->host('static')?>/img/flechamenu.png" alt="">
        </div> -->
        
      </div>
    <div class="footer">
          <nav class="fo">
            <ul class="fa">
              <li>
                <a href="<?php echo $this->basePath(); ?>/nosotros">Nosotros</a>
              </li>
              <li>
                <a href="<?php echo $this->basePath(); ?>/terminos">Términos y condiciones</a>
              </li>
              <li>
                <a href="<?php echo $this->basePath(); ?>/contactenos">Contáctenos</a>
              </li>
              <li>
                <div class="ups-crap btn-group dropup">
                  <button class="ups-dev dropdown-toggle" data-toggle="dropdown">Más buscados<span class="caret"></span></button>
                  <ul class="dropdown-menu">
                    <li><a href="<?php echo $this->basePath(); ?>/buscar?q=ceviche">Ceviche</a></li>
                    <li><a href="<?php echo $this->basePath(); ?>/buscar?q=lomo saltado">Lomo saltado</a></li>
                    <li><a href="<?php echo $this->basePath(); ?>/buscar?q=arroz con pollo">Arroz con pollo</a></li>
                  </ul>
                </div><!-- /btn-group -->
              </li>
            </ul>
          </nav>
      <footer class="footer-ie8">
        <p>
          Desarrollado por ISG - Innovations Systems Group  - Derechos Reservados
        </p>
      </footer>
    </div>
</div>
     
      <script src="<?php echo $this->basePath()?>/js/vendor/jquery.placeholder.min.js"></script> 
       <script src="<?php echo $this->basePath()?>/js/vendor/mosaic.js"></script>             
      <script src="<?php echo $this->basePath()?>/js/aplicacion.js"></script>
      <script type="text/javascript" src="<?php echo $this->basePath()?>/js/bootstrap-dropdown.js"></script>
    </body>
</html>
