<?php echo $this->doctype(); ?>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <title>Lista del Sabor</title>
        <meta name="description" content="ListaDelSabor.com es una lista de los platos más buscados y mejor recomendados en el Perú, en ella ubicarás sus datos, los restaurantes que lo venden y su valoración por los comensales">
        <meta name="viewport" content="width=device-width">
        <link href="/img/favicon.ico" rel="shortcut icon" type="image/x-icon"/>             
        <script src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false"></script>         
          <script src="<?php echo $this->basePath()?>/js/lib/jquery-1.8.3.min.js"></script>  
        <?php echo $this->headLink()->prependStylesheet($this->basePath() . '/css/estilos.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

        <script type="text/javascript">
          function initialize() {
            var centerLng = new google.maps.LatLng(-12.111858,-77.016091);
            var styles = [
              {
                stylers: [
                  { hue: "#00ffe6" },
                  { saturation: -20 }
                ]
              },{
                featureType: "road",
                elementType: "geometry",
                stylers: [
                  { lightness: 100 },
                  { visibility: "simplified" }
                ]
              },{
                featureType: "road",
                elementType: "labels",
                stylers: [
                  { visibility: "off" }
                ]
              }
            ];
            var myOptions = {
              zoom: 14,
              center: centerLng,
              scrollwheel: false,
              navigationControl: false,
              mapTypeControl: false,
              scaleControl: false,
              draggable: false,
              streetViewControl: false,
              styles: styles,
              mapTypeId: google.maps.MapTypeId.ROADMAP
            };
            var map = new google.maps.Map(document.getElementById("map_canvas"),
                myOptions);
          }
        </script>
    </head>

  <body class="lista-<?php echo $this->clase; ?>" onload="initialize()">
    <div id="map_canvas" style="position: fixed!important; top: 0; bottom: 0; left: 0; right: 0; z-index: 0;"></div>
    <div class="contenido">
      <div class="content-sidebar">
        <div class="contenido-busqueda">
          <div class="content-sidebar-ho">
          <a class="title-home-listado" href="<?php echo $this->basePath(); ?>/" title="Listado del Sabor">
              <h1>
              <img src="/img/logo.png" alt="logo">
            </h1>
          </a>
          <span class="logan-1" style="font-size: 3.1em;text-align: right;">-</span> 
          <span class="logan" style="width: 54%;">..y hoy, ¿qué se te antoja?</span> 
          <span class="logan-1" style="font-size: 3.1em;  text-align: right;">-</span>
          <div class="fec"><img src="/img/flecha-1.png" alt=""></div>
            <form  accept-charset="utf-8" method ="get" class="form-horizontal" id="search" action='<?php echo $this->url; ?>/application/index/ver'>
              <input id="q" name="q" type="text" placeholder="Escribe el nombre del plato" />
              <input type="submit"  class="btn btn-search-home" value="Buscar"/>
            </form>             
            <div class="final">
                <img src="/img/responsive.png" alt="" style="padding: 37px 10px;">
              </div>

              <div class="solicitar-publicacion">
                <a href="/application/index/solicita" class="btn btn-warning btn-soli">Solicite su publicación</a>
              </div>
          </div>
          </div><!--Fin del sidebar-->
      </div>

      <div class="contenido-plato">         
        <?php echo $this->content; ?>
       
        <div class="subir">
          <a href="#top"><img src="/img/scroll-top.png" alt=""></a>
        </div>
        <!--  <div class="arrow">
            <img src="/img/flechamenu.png" alt="">
        </div> -->
        
      </div>
    <div class="footer">
          <nav class="fo">
            <ul class="fa">
              <li>
                <a href="/application/index/nosotros">Nosotros</a>
              </li>
              <li>
                <a href="/application/index/terminos">Términos y condiciones</a>
              </li>
              <li>
                <a href="/application/index/contactenos">Contáctenos</a>
              </li>
              <li>
                <div class="ups-crap btn-group dropup">
                  <button class="ups-dev dropdown-toggle" data-toggle="dropdown">Más buscados<span class="caret"></span></button>
                  <ul class="dropdown-menu">
                    <li><a href="<?php echo $this->basePath(); ?>/application/index/ver?q=ceviche">Ceviche</a></li>
                    <li><a href="<?php echo $this->basePath(); ?>/application/index/ver?q=lomo saltado">Lomo saltado</a></li>
                    <li><a href="<?php echo $this->basePath(); ?>/application/index/ver?q=arroz con pollo">Arroz con pollo</a></li>
                  </ul>
                </div><!-- /btn-group -->
              </li>
            </ul>
          </nav>
      <footer>
        <p>
          Desarrollado por ISG - Innovations Systems Group  - Derechos Reservados
        </p>
      </footer>
    </div>
</div>
     
      <script src="<?php echo $this->basePath()?>/js/vendor/mosaic.js"></script>            
      <script src="<?php echo $this->basePath()?>/js/aplicacion.min.js"></script>
      <script type="text/javascript" src="<?php echo $this->basePath()?>/js/bootstrap-dropdown.js"></script>
    </body>
</html>
