<?php echo $this->doctype(); ?>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <title>Administración Restaurante</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width">
        
        <script src="https://maps.googleapis.com/maps/api/js?sensor=false"></script>
       
   
       
       
<!--         <script data-main="/js/main" src="<?php echo $this->basePath()?>/js/require.js"></script>  -->
         <script src="<?php echo $this->basePath()?>lib/jquery-1.8.3.min.js"></script> 
         <script src="<?php echo $this->basePath()?>lib/bootstrap.min.js"></script> 
         <script src="<?php echo $this->basePath()?>vendor/jquery.validate.js"></script> 
         <script src="<?php echo $this->basePath()?>vendor/gmap3.min.js"></script> 
         <script src="<?php echo $this->basePath()?>/js/main.js"></script> 
         
        <?php echo $this->headLink()->prependStylesheet($this->basePath() . '/css/main.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>                                
                                   
    </head>
    <body>
            <div class="container-fluid">
            <div class="row-fluid">
                <!-- cabecera-->
                  <div class="span12">
                        <div class="navbar navbar-inverse nav">
                        <div class="navbar-inner">              
                            <a class="brand" href="/">AREA ADMINISTRACION</a>
                            <div class="nav-collapse collapse">
                              <ul class="nav">
                              <li class="active"><a href="<?php echo $this->basePath();?>/usuario"><i class="icon-home icon-white"></i> MODULO USUARIOS</a></li>
                              <li class="divider-vertical"></li>
                              <li ><a href="<?php echo $this->basePath();?>/restaurante"><i class="icon-file icon-white"></i> MODULO RESTAURANTES</a></li>
                              <li class="divider-vertical"></li>
                              <li><a href="#"><i class="icon-envelope icon-white"></i> MODULO PLATOS</a></li>
                              <li class="divider-vertical"></li>                             
                              </ul>
                              </div>
                          
                                  <div class="nav-collapse collapse">
                                    <div class="pull-right">
                                    <ul class="nav pull-right">
                                        <li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown">Bienvenido, Admin <b class="caret"></b></a>
                                            <ul class="dropdown-menu">
                                                <li><a href="#"><i class="icon-cog"></i> Configuración</a></li>
                                                  <li class="divider"></li>
                                                <li><a href="/auth/logout"><i class="icon-off"></i> Logout</a></li>
                                            </ul>
                                        </li>
                                    </ul>
                                    </div>            
                                  </div>
                        </div>
                         </div>
                   </div>
                  <div class="row-fluid">
                <!-- sidebar-->
              <!--   <div class="span2">
                    <ul class="nav nav-list">
                        <li class="active" ><a href="#"><i class="icon-home "></i> INICIO</a></li>
                        <li class="nav-header">USUARIOS</li>
                        <li><a href=""> <i class="icon-user"></i> Listado Usuarios</a></li>
                        <li><a data-toggle="modal" href="<?php echo $this->basePath();?>/usuario/index/agregarusuario"><i class="icon-pencil"></i> Ingresar Usuario</a></li>
                        <li><a data-toggle="modal" href="#ins-rol"><i class="icon-pencil"></i> Ingresar rol</a></li>
                        <li class="nav-header ">RESTAURANTES</li>
                        <li ><a href="restaurante.php" ><i class="icon-bookmark"></i> Listado Restaurante</a></li>
                        <li><a data-toggle="modal" href="#ing-restaurante"><i class="icon-pencil"></i> Ingresar Restaurante</a></li>
                        <li><a data-toggle="modal" href="#espe_rest"><i class="icon-pencil"></i> Ingresar Especialidad</a></li>
                        <li ><a href="#" ><i class="icon-bookmark"></i> Listado Locales</a></li>
                        <li class="nav-header">PLATOS</li>
                            <li><a href="#"><i class="icon-inbox"></i> Listado Platos</a></li>
                        </ul>
                </div> -->
  
                <?php echo $this->content; ?>
                
               </div>
      </div> 
       </div>
          </body>
</html>
    



