<?php


$title = 'Add new album';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('hola', array('action' => 'add')));
$form->prepare();
echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('nombre'));
echo $this->formRow($form->get('apellido'));
echo $this->formRow($form->get('pass'));
echo $this->formRow($form->get('email'));
echo $this->formRow($form->get('rol'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();