<?php
// module/Album/view/album/album/index.phtml:

$title = 'My albums';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url('album', array('action'=>'add'));?>">Add new album</a>
</p>

<table class="table">
<tr>
    <th>Title</th>
    <th>Artist</th>
    <th>&nbsp;</th>
</tr>
<?php foreach ($albums as $album) : ?>
<tr>
    <td><?php echo $this->escapeHtml($album->va_nombre);?></td>
    <td><?php echo $this->escapeHtml($album->va_apellidos);?></td>
    <td>
        <a href="<?php echo $this->url('hola',
            array('action'=>'a', 'in_id' => $album->in_id));?>">Edit</a>
        <a href="<?php echo $this->url('album',
            array('action'=>'delete', 'in_id' => $album->in_id));?>">Delete</a>
    </td>
</tr>
<?php endforeach; ?>
</table>