<?php echo $this->doctype(); ?>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <title>Administración Restaurante</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width">
        
        <script src="https://maps.googleapis.com/maps/api/js?sensor=false"></script>
       
   
       
       
<!--         <script data-main="/js/main" src="<?php echo $this->basePath()?>/js/require.js"></script>  -->
         <script src="<?php echo $this->basePath()?>/js/lib/jquery-1.8.3.min.js"></script> 
         <script src="<?php echo $this->basePath()?>/js/vendor/jquery.sidr.min.js"></script> 
         <script src="<?php echo $this->basePath()?>/js/lib/bootstrap.min.js"></script> 
         <script src="<?php echo $this->basePath()?>/js/vendor/jquery.validate.js"></script> 
         <script src="<?php echo $this->basePath()?>/js/vendor/gmap3.min.js"></script> 
            <script src="<?php echo $this->basePath()?>/js/vendor/jquery.raty.min.js"></script> 
         <script src="<?php echo $this->basePath()?>/js/main.js"></script> 
         
        <?php echo $this->headLink()->prependStylesheet($this->basePath() . '/css/main.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.css') ?>                                
                                   
    </head>
    <body>  
        <?php echo $this->key ?>
            <div class="container-fluid">
            <div class="row-fluid">
                <!-- cabecera-->
                  <div class="span12">
                        <div class="navbar navbar-inverse nav">
                        <div class="navbar-inner">              
                            <a class="brand" href="/">Sistema Platos</a>
                                              
                                  <div class="nav-collapse collapse">
                                    <div class="pull-right">
                                    <ul class="nav pull-right">
                                        <li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown">Bienvenido, Admin <b class="caret"></b></a>
                                            <ul class="dropdown-menu">
                                                <li><a href="#"><i class="icon-cog"></i> Configuración</a></li>
                                                  <li class="divider"></li>
                                                <li><a href="/auth/logout"><i class="icon-off"></i> Logout</a></li>
                                            </ul>
                                        </li>
                                    </ul>
                                    </div>            
                                  </div>
                        </div>
                         </div>
                   </div>
                  <div class="row-fluid">
  <div class="contenido"> 
                <?php echo $this->content; ?>
  </div>
               </div>
      </div> 
       </div>
          </body>
</html>
    



