
<?php
// module/Album/view/album/album/index.phtml:

$title = 'My albums';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>


<table class="table">
<tr>
    <th>Title</th>
    <th>Artist</th>
    <th>&nbsp;</th>
</tr>
<?php foreach ($this->restaurantes as $album) : ?>
<tr>
    <td><?php echo $this->escapeHtml($album->va_razon_social);?></td>
    <td><?php echo $this->escapeHtml($album->va_web);?></td>
    <td>
       
    </td>
</tr>
<?php endforeach; ?>
</table>