<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'LoginFace\Module'                       => __DIR__ . '/Module.php',
    'LoginFace\Controller\AuthController'    => __DIR__ . '/src/LoginFace/Controller/AuthController.php',
    'LoginFace\Controller\SuccessController' => __DIR__ . '/src/LoginFace/Controller/SuccessController.php',
    'LoginFace\Model\MyAuthStorage'          => __DIR__ . '/src/SLoginFace/Model/MyAuthStorage.php',
//    'LoginFace\Model\User'                   => __DIR__ . '/src/LoginFace/Model/User.php',
);