<?php if ($_GET['m']==1) { ?> <div class="row-fluid">
      <div class="alert alert-margin alert-message">
        <button type="button" class="close" data-dismiss="alert">×</button>
        <?php  echo 'Tu cuenta está casi lista para usarse, solo tienes que activarla desde tu correo electrónico'; ?>
      </div>
    </div> <?php } ?>
<?php if($this->mensaje){?>
    <div class="row-fluid">
      <div class="alert alert-margin alert-message">
        <button type="button" class="close" data-dismiss="alert">×</button>
        <?php  echo $this->mensaje; ?>
      </div>
    </div>
   <?php } ?>
        <?php
          $form = $this->form;
          $form->setAttributes(array(
           'action' => $this->url.'/registrarse',
           'method' => 'post',
           'class'=>'span12 form-crear-usuario',
           'id'=>'registro'
          ));
          $form->prepare();
          echo $this->form()->openTag($form);
        ?>

          <div >
          <?php echo $this->formHidden($form->get('in_id'));?>
          <span>(<strong> * </strong>) Por favor complete los campos requeridos</span>
            <p>
            <label for=""><strong> * </strong>Nombre Completo</label>
            <?php echo $this->formRow($form->get('va_nombre_cliente'));?>
            </p>
            <p>
            <label for=""><strong> * </strong>Correo Electrónico</label>
            <?php echo $this->formRow($form->get('va_email'));?>
            </p>
            <p>
            <label for=""><strong> * </strong>Contraseña</label>
            <?php echo $this->formRow($form->get('va_contrasena'));?>
            </p>
            <p>
            <label for=""><strong> * </strong>Confirmar contraseña</label>
            <?php echo $this->formRow($form->get('verificar_contrasena'));?>
            </p>
            
            <p>
            <label for=""><strong> * </strong>notificaciones</label>
            <?php echo $this->formRow($form->get('va_notificacion'));?>
            </p>
            <?php echo $this->formSubmit($form->get('submit'));?>
        </div>
      
        <?php echo $this->form()->closeTag();?>
          
          

    

   
<script type="text/javascript">
  $(document).ready(function(){
    $(".alert-message").alert();
    window.setTimeout(function() { $(".alert-message").alert('close'); }, 15000);
  });
</script>