
<?php
$title = 'My album';
$this->headTitle($title);
echo $this->hola;
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<table class="table">
<tr><th>Id</th>
    <th>Titulo</th>
    <th>email</th>
   <!-- <th>Artista</th>
    <th>&nbsp;</th>-->
</tr>

<?php foreach($yea as $yea)  : ?>
<tr>
    <td><?php echo $yea['va_nombre' ];?></td>
    <td><?php echo $yea['va_apellidos'];?></td>
    <td>  <?php echo $yea['va_email'];?></td>
    <td><?php echo $yea['id_pais'];?></td>-->
    <td><a href="<?php echo $this->basePath();?>/application/index/ver/<?php echo $yea['in_id'];?>" title="ver valores">ver</a></td>
    <td><a href="<?php echo $this->basePath();?>/application/index/add/<?php echo $yea['in_id'];?>" title="ver valores">eliminar</a></td>
</tr>
<?php endforeach; ?>
