
<?php
$title = 'My album';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<table class="table">
<tr><th>Id</th>
    <th>nombre</th>
    <th>apellido</th>
    <th>email</th>
    <th>estado</th>
    <th>rol</th>
    <th>&nbsp;</th>
</tr>

<?php foreach($yea as $yea)  : ?>
<tr>
    <td><?php echo $yea['in_id' ];?></td>
    <td><?php echo $yea['va_nombre' ];?></td>
    <td><?php echo $yea['va_apellidos'];?></td>
    <td><?php echo $yea['va_email'];?></td>
    <td><?php echo $yea['en_estado'];?></td>
    <td><?php echo $yea['va_nombre_rol'];?></td>
    <?php //print_r($yea); ?>
</tr>
<?php endforeach; ?>
</table>