<?php


$title = 'Agregar nuevo local';
$this->headTitle($title);
?>

<div class="span8">
<?php
$form = $this->form;
//$form->setAttribute('action', $this->url('usuario', array('action' => 'add')));

$form->setAttributes(array(
    'action' => $this->url.'/local/index/agregarlocal',
    'method' => 'post',
    'class'=>'form-horizontal'
));
$form->prepare();

echo $this->form()->openTag($form);
?><h3><?php echo $this->escapeHtml($title); ?></h3>
<?php
echo $this->formHidden($form->get('in_id'));
?>
<?php
echo $this->formHidden($form->get('ta_restaurante_in_id'));
?>
<h5><?php echo $this->id ;?></h5>
<div class="control-group span5"><?php echo $this->formRow($form->get('va_telefono'));?></div><?php?>
<div class="control-group span5"><?php echo $this->formRow($form->get('va_horario'));?></div ><?php?>
<div class="control-group span5"><?php echo $this->formRow($form->get('va_horario_opcional'));?></div ><?php?>
<div class="control-group span5"><?php echo $this->formRow($form->get('va_rango_precio'));?></div><?php?>
<div class="control-group span5"><?php echo $this->formRow($form->get('ta_dia_in_id'));?></div><?php?>
<div class="control-group span5 "><?php echo $this->formRow($form->get('pais'));?></div><?php?>
<div class="control-group span5"><?php echo $this->formRow($form->get('departamento'));?></div><?php?>
<div class="control-group span5"><?php echo $this->formRow($form->get('provincia'));?></div><?php?>
<div class="control-group span5"><?php echo $this->formRow($form->get('distrito'));?></div><?php?>
<div class="control-group span5">
  <label for="">Seleccione Servicio que ofrece</label>
  <label class="checkbox inline">
   <?php echo $this->formRow($form->get('servicio'));?> 
  </label>
</div>

<div class="control-group span5"><?php echo $this->formRow($form->get('va_direccion'));?></div><?php?>
<div class="control-group"><?php echo $this->formRow($form->get('de_latitud'));?></div>
<div class="control-group"><?php echo $this->formRow($form->get('de_longitud'));?></div>
<div class="control-group span5">
                              <label>Encontrar latitud y longitud</label>
                              <div><input type="text" maxlength="100" id="address" class="span10"/> <input type="button" class="btn btn-info" id="search" value="Buscar" /></div><br/>
                              <div id='map_canvas' style="height:200px;width:700px;"></div>                           
                             </div>

<div class="control-group span12"><?php echo $this->formSubmit($form->get('submit'));?></div><?php
echo $this->form()->closeTag();?> </div> 
</div>
<script>
	$(document).ready(function(){
		var id_r = $('h5').text();
console.log(id_r);
$('#ta_restaurante_in_id').val(id_r);
	})
</script>