<?php


$title = 'Agregar nuevo local';
$this->headTitle($title);
?>


<?php
$form = $this->form;
//$form->setAttribute('action', $this->url('usuario', array('action' => 'add')));

$form->setAttributes(array(
    'action' => $this->url.'/local/index/agregarlocal',
    'method' => 'post'
));
$form->prepare();

echo $this->form()->openTag($form);
?><h3><?php echo $this->escapeHtml($title); ?></h3>
<?php
echo $this->formHidden($form->get('in_id'));
?><div class="control-group "><?php echo $this->formRow($form->get('va_telefono'));?></div><?php?>
<div class="control-group "><?php echo $this->formRow($form->get('va_horario'));?></div ><?php?>
<div class="control-group "><?php echo $this->formRow($form->get('va_rango_precio'));?></div><?php?>
<div class="control-group "><?php echo $this->formRow($form->get('ta_dia_in_id'));?></div><?php?>
<div class="control-group "><?php echo $this->formRow($form->get('pais'));?></div><?php?>
<div class="control-group "><?php echo $this->formRow($form->get('departamento'));?></div><?php?>
<div class="control-group "><?php echo $this->formRow($form->get('provincia'));?></div><?php?>
<div class="control-group "><?php echo $this->formRow($form->get('distrito'));?></div><?php?>
<div class="control-group "><?php echo $this->formRow($form->get('va_direccion'));?></div><?php?>
<div class="control-group "><?php echo $this->formSubmit($form->get('submit'));?></div><?php
echo $this->form()->closeTag();?> </div> 