<?php


$title = 'Editar local';
$this->headTitle($title);
?>

<div class="span10">
<?php
$form = $this->form;
//$form->setAttribute('action', $this->url('usuario', array('action' => 'add')));

$form->setAttributes(array(
    'action' => $this->url.'/local/index/editarlocal?id='.$this->id,
    'method' => 'post',
    'in_id'   =>$this->id,
));
$form->prepare();



echo $this->form()->openTag($form);
?><h3><?php echo $this->escapeHtml($title); ?></h3>
<?php
echo $this->formHidden($form->get('in_id'));
?>
<?php
echo $this->formHidden($form->get('ta_restaurante_in_id'));
?>


<?php
echo $this->formHidden($form->get('h_pais'));
?>
<?php
echo $this->formHidden($form->get('h_departamento'));
?>
<?php
echo $this->formHidden($form->get('h_provincia'));
?>
<?php
echo $this->formHidden($form->get('h_distrito'));
?>


<h5><?php echo $this->id ;?></h5>

<div class="control-group "><?php echo $this->formRow($form->get('servicio'));?></div>

<div class="control-group "><?php echo $this->formRow($form->get('de_latitud'));?></div>
<div class="control-group "><?php echo $this->formRow($form->get('de_longitud'));?></div>
<div class="control-group "><?php echo $this->formRow($form->get('va_telefono'));?></div><?php?>
<div class="control-group "><?php echo $this->formRow($form->get('va_horario'));?></div ><?php?>
<div class="control-group "><?php echo $this->formRow($form->get('va_horario_opcional'));?></div ><?php?>
<div class="control-group "><?php echo $this->formRow($form->get('va_rango_precio'));?></div><?php?>
<div class="control-group "><?php echo $this->formRow($form->get('ta_dia_in_id'));?></div><?php?>
<div class="control-group">
	<label for="">Seleccione Servicio que ofrece</label>
	<label id="servicio_local"></label>
</div>

<div class="control-group "><?php echo $this->formRow($form->get('pais'));?></div><?php?>
<div class="control-group "><?php echo $this->formRow($form->get('departamento'));?></div><?php?>
<div class="control-group "><?php echo $this->formRow($form->get('provincia'));?></div><?php?>
<div class="control-group "><?php echo $this->formRow($form->get('distrito'));?></div><?php?>

<div class="control-group "><?php echo $this->formRow($form->get('va_direccion'));?></div><?php?>
<div class="control-group span12">
                              <label>Encontrar latitud y longitud</label>
                              <div><input type="text" maxlength="100" id="address" class="span10"/> <input type="button" class="btn btn-info" id="search" value="Buscar" /></div><br/>
                              <div id='map_canvas' style="height:200px;"></div>                           
                             </div>
<div class="control-group "><?php echo $this->formSubmit($form->get('submit'));?></div><?php
echo $this->form()->closeTag();?> </div> 
</div>
<script>
	$(document).ready(function(){
		  var id_r = $('h5').text();
      $('#ta_restaurante_in_id').val(id_r);
       var pais=parseInt($('#pais').val());
         var depa=parseInt($('#h_departamento').val());
         var prov=parseInt($('#h_provincia').val());
         var dis=parseInt($('#h_distrito').val());
      $.getJSON('/local/index/jsondepartamento',function(data){
              $.each(data,function(i,val){              
                $('#departamento').append( "<option value=" + val.in_iddep + ">" + val.ch_departamento + " </option>");
                   $("#departamento" +" option[value=" +depa +"]").attr("selected","selected");                        
          });          
        
      });
    
  
    var url="/local/index/jsonprovincia?iddepa=" + depa;
     console.log(depa);
     console.log(prov);
     console.log(dis);
          $.getJSON(url,function(data){
                  $("#provincia").empty();  
                $.each(data,function(i,val){ 
                                 
                    $('#provincia').append( "<option value=" + val.in_idprov + ">" + val.ch_provincia + " </option>");      $("#provincia" +" option[value=" +prov +"]").attr("selected","selected");                          
                          });  
         });
    var url2="/local/index/jsondistrito?iddepa=" + depa + "&iddpro=" + prov
      $.getJSON(url2,function(data){
         $("#distrito").empty();
        $("#distrito").append("<option value=''>Seleccione</option>");
    $.each(data,function(i,val){  
          
                $('#distrito').append( "<option value=" + val.in_iddis + " >" + val.ch_distrito + " </option>");   
                  $("#distrito" +" option[value=" +dis +"]").attr("selected","selected");
          });  
     });
        var url3="/local/index/jsonservicios?id=" + id
    $.getJSON(url3,function(data){ 
             
            $.each(data,function(i,val){
            $(".checkbox").each(function(){ 
              var va = $(this).attr('value');
              console.log(val.ta_servicio_local_in_id);
           if (va==val.ta_servicio_local_in_id ){
                $(this).prop("checked" , true ); 
             } 
             });                       
    });
});



	})
</script>