
   <div class="row-fluid">

    <div class="span4">
      <div class="input-append"> 
    <form name='form_busqueda'class="form-search" action='/local/index' method ="post">
   <div class="control-group">

    <label class="ra radio">Buscar:
    <input type='text' name='texto' id="texto" placeholder="Restaurant,Distrito" />
    <input type="submit" class="btn" name="submit" value="Buscar">
    </div>
    </div>
    </form>
    </div>
    </div>

<div class="row-fluid">
<div class="span12">
<table class="table table-bordered table-hover">
    <thead>  
        <tr>
          <th>#</th> 
            <th>Nombre de Restaurant</th>
            <th>Telefono</th>
            <th>Horario</th>
            <th>Rango de precio</th>
            <th>Direccion</th>
            <th>Pais</th>
            <th>Departamento</th>
            <th>Provincia</th>
            <th>Distrito</th>
        </tr>
    </thead>
    
        <?php $count = 1;
    foreach ($this->locales  as $local) :// foreach ($this->paginator as $usuario) :
        ?>
        <tr>
            <td><?php echo $count++ ?></td>
            <td><?php echo $this->escapeHtml($local->va_nombre); ?></td> 
            <td><?php echo $this->escapeHtml($local->va_telefono); ?></td>
            <td><?php echo $this->escapeHtml($local->va_horario); ?></td>
            <td><?php echo $this->escapeHtml($local->va_rango_precio); ?></td>
            <td><?php echo $this->escapeHtml($local->va_direccion); ?></td>
            <td><?php echo $this->escapeHtml($local->ch_pais); ?></td>
            <td><?php echo $this->escapeHtml($local->ch_departamento); ?></td>
            <td><?php echo $this->escapeHtml($local->ch_provincia); ?></td>
            <td><?php echo $this->escapeHtml($local->ch_distrito); ?></td>
            
            
            <td><a data-id="<?php echo $this->escapeHtml($local->in_id); ?>" href="/local/index/editarlocal/<?php echo $local->in_id;?>" class='modificar btn btn-info'><i class='icon-edit icon-white'></i>Editar</a></td>
            <td><a data-id="<?php echo $this->escapeHtml($local->in_id); ?>" href="/local/index/editarlocal/<?php echo $local->in_id;?>" class='eli btn btn-danger'><i class='icon-trash icon-white'></i>Eliminar</a> </td>
        </tr>

<?php endforeach; ?>
    
</table>
</div>
</div>