<h1><?php echo $this->titulo?></h1>
<?php
$form = $this->form;
$form->prepare();
$form->setAttributes(array(
    'action' => $this->url.'/application/index/actualizarusuario',
    'method' => 'post',
    'in_id'     => $this->in_id,
));
$formLabel = $this->plugin('formLabel');
//$formValue = $this->getValue('getValue');

echo $this->form()->openTag($form);
?>

<div class="form_element">

<?php
    $name = $form->get('nombre');

    echo $formLabel->openTag().$name->getOption('label')." ";
    echo $formLabel->closeTag();
    echo $formLabel->closeTag();
    
    echo $this->formInput($name);

?>
</div>
<div class="form_element">

<?php
    $apellido = $form->get('apellido');
   // echo $this->ye['apellido'];
    echo $formLabel->openTag().$apellido->getOption('label')." ";
    echo $this->ye['apellido'];
    echo $formLabel->closeTag();
    echo $this->formInput($apellido);
?>
</div>
<div class="form_element">
<?php
    $pass = $form->get('pass');
    echo $formLabel->openTag().$pass->getOption('label')." ";
    echo $this->ye['pass'];
    echo $this->formElementErrors($name);
    //echo $this->setValue() == $this->ye['email']);
    echo $formLabel->closeTag();
    echo $this->formInput($pass);
?>
</div>


<div class="form_element">

<?php
    $email = $form->get('email');
    echo $formLabel->openTag().$email->getOption('label')." ";
    echo $this->ye['email'];
    echo $formLabel->closeTag();
    echo $this->formInput($email);
?>
</div>
     <div class="form_element">
    <?php
    $pais = $form->get('rol');
    echo $formLabel->openTag().$pais->getOption('label')." ";
    echo $this->ye['rol'];
    echo $formLabel->closeTag();
    echo $this->formInput($pais);
    ?></div>
<hr />
<?php echo $this->formHidden($form->get('oculto')) ?>
<?php echo $this->formElement($form->get('send')) ?>
<?php echo $this->form()->closeTag() ?>