<?php

$title = 'Contactar';
$this->headTitle($title);
?>
<script src="<?php echo $this->basePath()?>/js/vendor/jquery.validate.js"></script>
<div class="content-left">
	<div class="descrip-product">
		<div class="contenido-static">
			<h2>Contactenos</h2>
			<?php
			$form = $this->form;
			//$form->setAttribute('action', $this->url('usuario', array('action' => 'add')));

			$form->setAttributes(array(
			    'action' => $this->url.'/contactenos',
			    'method' => 'post',
			    'class' => 'form-horizontal'
			));
			$form->prepare();

			echo $this->form()->openTag($form);
			echo $this->formHidden($form->get('in_id'));
			?>
			<?php
			$form = $this->form;
			//$form->setAttribute('action', $this->url('usuario', array('action' => 'add')));

			$form->setAttributes(array(
			    'action' => $this->url.'/usuario/index/agregarusuario',
			    'method' => 'post'
			    
			));
			$form->prepare();

			echo $this->form()->openTag($form);
			echo $this->formHidden($form->get('in_id'));

			?>
			<div class="control-group">
			    <label class="control-label" for="inputName">Nombre<span class="red">*</span>:</label>
			    <div class="controls">
			      <?php echo $this->formRow($form->get('nombre'));?>
			    </div>
			</div>
			<div class="control-group">
			    <label class="control-label" for="inputEmail">Email<span class="red">*</span>:</label>
			    <div class="controls">
			      <?php echo $this->formRow($form->get('email'));?>
			    </div>
			</div>
			<div class="control-group">
			    <label class="control-label" for="inpuNombre">Asunto<span class="red">*</span>:</label>
			    <div class="controls">
			      <?php echo $this->formRow($form->get('asunto'));?>
			    </div>
			</div>
			<div class="control-group">
			    <label class="control-label" for="inputEmail">Mensaje<span class="red">*</span>:</label>
			    <div class="controls">
			      <?php echo $this->formRow($form->get('mensaje'));?>
			    </div>
			</div>
			<div class="control-group">
			    <div class="controls">
			      <?php echo $this->formSubmit($form->get('submit'));?>
			    </div>
			</div>

		</div>
	</div>
	
</div>

<script type="text/javascript">

$('#submitbutton').click(function(){
	submitForm();
});

function submitForm(){ 
	var validator = $("#application").validate({ 
	rules: {
		nombre: {
			required: true
		}, 
		email: {
			required: true,
			email: true
		}, 
		asunto: "required",
		mensaje: "required"
		
	}, 
	errorElement: "em", 
	messages: { 
		name: "Ingrese su nombre completo", 
		email: {
			required: "Ingrese su correo electrónico",
			email: "Ingrese un correo valido"
		}, 
		asunto: "Ingrese el asunto", 
		mensaje: "Ingrese el mensaje"
	} 
	}); 
	if(validator.form()){ // validation perform 
		$('form#application').attr({action: 'mycontroller'});	 
		$('form#application').submit(); 
	} 
}

</script>