 <?php
                        header('Content-Type: text/html; charset=utf-8');
                        $limit = 9;             
                        $query = isset($_REQUEST['q']) ? $_REQUEST['q'] : false ;
                        $consulta =array('fq'=> 'en_estado:activo AND distrito:'.$_REQUEST['fq'],
                                       'sort'=>'en_destaque desc',
                            'wt'=>'json');
                        
                      
                        $results = false;
                        if ($query)
                        { 
                          require './vendor/SolrPhpClient/Apache/Solr/Service.php';
                          $solr = new Apache_Solr_Service('192.168.1.44', 8983, '/solr/');
                          if (get_magic_quotes_gpc() == 1)
                          {
                            $query = stripslashes($query);
                          }
                          try
                          {
                            $results = $solr->search($query, 0, $limit, $consulta );

                          }
                          catch (Exception $e)
                          {
                          
                                echo("<html><head><title>SEARCH EXCEPTION</title><body><pre>{$e->__toString()}</pre></body></html>");
                                     
                          }
                        }

                        ?>
                        <form  accept-charset="utf-8" method="get" class="form-horizontal" id="search" autocomplete="on" >
                              buscar plato:<input id="r" name="q" type="text" placeholder="Escribe el nombre del plato" value="<?php echo htmlspecialchars($query, ENT_QUOTES, 'utf-8'); ?>"/>
                  por distrito:
                 <SELECT name="fq" id="fq" class="span2">
                <OPTION value="">seleccione:</OPTION>
                   <?php  foreach ($this->distritos as $distritos) : ?>
                  <OPTION   value="<?php echo $distritos['ch_distrito']; ?>"><?php echo $distritos['ch_distrito']; ?></OPTION>
                  <?php endforeach; ?>
                 </SELECT>
             <input type="submit"/>
                       <!-- 
                            <?php
                            if ($results)
                            {
                              $total = (int) $results->response->numFound;
                              $start = min(1, $total);
                              $end = min($limit, $total);
                            ?> -->
                               <div>Resultados <?php echo $start; ?> - <?php echo $end;?> de <?php echo $total; ?>:</div> 
                                <div>Resultados <?php echo $fq; ?>:</div> 
                           
                         </form> 

 <?php 
                foreach ($results->response->docs as $doc)
                          {
                      ?> <li>
                        <table style="border: 1px solid black; text-align: left">
                         <tr><td>id: <?php echo htmlspecialchars($doc->id, ENT_QUOTES, 'utf-8'); ?></td> </tr>
                         <tr><td>nombre plato: <?php echo htmlspecialchars($doc->name, ENT_QUOTES, 'utf-8'); ?></td></tr>
                         <tr><td>descripcion: <?php echo htmlspecialchars($doc->tx_descripcion, ENT_QUOTES, 'utf-8'); ?></td></tr>
                         <tr><td>precio: <?php echo 'S/ '.  htmlspecialchars($doc->va_precio, ENT_QUOTES, 'utf-8'); ?></td></tr>
                         <tr><td>direccion: <?php echo htmlspecialchars($doc->va_direccion, ENT_QUOTES, 'utf-8'); ?></td></tr>
                         <tr><td>restaurante: <?php echo htmlspecialchars($doc->restaurante, ENT_QUOTES, 'utf-8'); ?></td></tr>
                         <tr><td>tipo de plato: <?php echo htmlspecialchars($doc->plato_tipo, ENT_QUOTES, 'utf-8'); ?></td></tr>
                          <tr><td>destacado: <?php echo htmlspecialchars($doc->en_destaque, ENT_QUOTES, 'utf-8'); ?></td></tr>
                          <tr><td>estado: <?php echo htmlspecialchars($doc->en_estado, ENT_QUOTES, 'utf-8'); ?></td></tr>
                          <tr><td>distrito: <?php echo htmlspecialchars($doc->distrito, ENT_QUOTES, 'utf-8'); ?></td></tr>
                         </table>
                            </li>
                      <?php
                          }
                      ?>   
                
                      <?php
                      }  else 
                           {
                         // echo 'no existen resultados para su busqueda';   
                           }
                      ?>  