 <div class="map-portada">
 <div class="guia">
          <img src="/img/globos.png" alt="">
</div>   

    <div class="sub subir-home">
      <div class="content-etiqueta-home">
        <p>Platos destacados</p>
      </div>
    </div>
    <div class="recomendados-platos primer-home">
      <ul>       
         <?php  foreach ($this->lista  as $list) : ?>
          <li>
               <div class="plato_r">
                    <input type="hidden" value="<?php echo htmlspecialchars($list->in_id, ENT_QUOTES, 'utf-8'); ?>">
                    <input type="hidden" name="pun" data-id="<?php echo htmlspecialchars($list->in_id, ENT_QUOTES, 'utf-8'); ?>"value="<?php echo htmlspecialchars($list->Puntaje, ENT_QUOTES, 'utf-8');?>">
                     <div class="mosaic-block cover">
                     <div class="mosaic-overlay"><span><?php echo htmlspecialchars($list->va_nombre, ENT_QUOTES, 'utf-8'); ?></span>
                     <img src="/imagenes/<?php echo htmlspecialchars($list->va_imagen, ENT_QUOTES, 'utf-8'); ?>" class="img-plato"><img src="img/mas.png" alt="" class="mas">
                     </div>
                     <a href="/platos/index/verplatos?id=<?php echo $list->in_id;?>" target="_blank" class="mosaic-backdrop">
                       <div class="details">
                           <h4><?php echo htmlspecialchars($list->va_nombre, ENT_QUOTES, 'utf-8'); ?></h4>
                           <p style="font-weight: bold;">Ingredientes</p>
                           <p style="font-size:0.9em;"> <?php echo htmlspecialchars($list->tx_descripcion, ENT_QUOTES, 'utf-8'); ?> </p>
                       </div>
                   </a>
                       </div>
                  <div class="foo">
                    <p class="nom_res"><?php echo htmlspecialchars($list->restaurant_nombre, ENT_QUOTES, 'utf-8'); ?></p>
                    <div class="pt">
                      <!--<p class="pre"><?php echo 'S/. '.  htmlspecialchars($list->va_precio, ENT_QUOTES, 'utf-8'); ?></p>-->
                      <p class="com"><?php echo $list->NumeroComentarios ?> <i class="icon-comment"></i></p>
                      <p id="<?php echo htmlspecialchars($list->in_id, ENT_QUOTES, 'utf-8');?>" class="punt"></p>
                    </div>
                  </div>
               </div>
              </li>
          <?php endforeach; ?>   
      </ul>
    </div>
     
     <!--Destaques segunda fila -->
     
    <div class="sub" id="cate-home" style="padding-top: 30px;">
      <div class="content-etiqueta-home">
        <p>Platos destacados</p>
      </div>
    </div>
    <div class="recomendados-platos">
      <ul>       
         <?php  foreach ($this->listaseg  as $list) : ?>
          <li>
               <div class="plato_r">
                    <input type="hidden" value="<?php echo htmlspecialchars($list->in_id, ENT_QUOTES, 'utf-8'); ?>">
                    <input type="hidden" name="pun" data-id="<?php echo htmlspecialchars($list->in_id, ENT_QUOTES, 'utf-8'); ?>"value="<?php echo htmlspecialchars($list->Puntaje, ENT_QUOTES, 'utf-8');?>">
                     <div class="mosaic-block cover">
                     <div class="mosaic-overlay"><span><?php echo htmlspecialchars($list->va_nombre, ENT_QUOTES, 'utf-8'); ?></span>
                     <img src="/imagenes/<?php echo htmlspecialchars($list->va_imagen, ENT_QUOTES, 'utf-8'); ?>" class="img-plato"><img src="img/mas.png" alt="" class="mas">
                     </div>
                     <a href="/platos/index/verplatos?id=<?php echo $list->in_id;?>" target="_blank" class="mosaic-backdrop">
                       <div class="details">
                           <h4><?php echo htmlspecialchars($list->va_nombre, ENT_QUOTES, 'utf-8'); ?></h4>
                           <p style="font-weight: bold;">Ingredientes</p>
                           <p style="font-size:0.9em;"> <?php echo htmlspecialchars($list->tx_descripcion, ENT_QUOTES, 'utf-8'); ?> </p>
                       </div>
                   </a>
                       </div>
                  <div class="foo">
                    <p class="nom_res"><?php echo htmlspecialchars($list->restaurant_nombre, ENT_QUOTES, 'utf-8'); ?></p>
                    <div class="pt">
                      <!--<p class="pre"><?php echo 'S/. '.  htmlspecialchars($list->va_precio, ENT_QUOTES, 'utf-8'); ?></p>-->
                      <p class="com"><?php echo $list->NumeroComentarios ?> <i class="icon-comment"></i></p>
                      <p id="<?php echo htmlspecialchars($list->in_id, ENT_QUOTES, 'utf-8');?>" class="punt"></p>
                    </div>
                  </div>
               </div>
              </li>
          <?php endforeach; ?>   
      </ul>
    </div>
     
<!--Valoracion fila -->
<div class="sub" style="margin-top: 0px;">
      <div class="content-etiqueta-home">
        <p>Platos valorados</p>
      </div>
    </div>
    <div class="recomendados-platos">
      <ul>
         <?php foreach ($this->listaval  as $list) : ?> 
              <li>
                <div class="plato_r">
                    <input type="hidden" value="<?php echo htmlspecialchars($list->in_id, ENT_QUOTES, 'utf-8');?>">
                    <input type="hidden" name="pun" data-id="<?php echo htmlspecialchars($list->in_id, ENT_QUOTES, 'utf-8'); ?>"value="<?php echo htmlspecialchars($list->Puntaje, ENT_QUOTES, 'utf-8');?>">
                        <div class="mosaic-block cover">
                          <div class="mosaic-overlay"><span><?php echo htmlspecialchars($list->va_nombre, ENT_QUOTES, 'utf-8');?></span>

                           <img src="/imagenes/<?php echo htmlspecialchars($list->va_imagen, ENT_QUOTES, 'utf-8'); ?>" class="img-plato"><img src="img/mas.png" alt="" class="mas">
                           </div>
                           <a href="/platos/index/verplatos?id=<?php echo $list->in_id;?>" target="_blank" class="mosaic-backdrop">

                             <div class="details">
                                 <h4><?php echo htmlspecialchars($list->va_nombre, ENT_QUOTES, 'utf-8'); ?></h4>
                                 <p style="font-weight: bold;font-size: 0.9em;">Ingredientes</p>
                                 <p style="font-size:0.9em;"><?php echo htmlspecialchars($list->tx_descripcion, ENT_QUOTES, 'utf-8'); ?> </p>
                             </div>
                         </a>
                             </div>
                             <div class="foo">
           <p class="nom_res"><?php echo htmlspecialchars($list->restaurant_nombre, ENT_QUOTES, 'utf-8');?></p>
           <div class="pt">
               <p class="pre"><?php echo 'S/. '.  htmlspecialchars($list->va_precio, ENT_QUOTES, 'utf-8'); ?></p>
               <p class="com"><?php echo $list->NumeroComentarios ?> <i class="icon-comment"></i></p>
           <p id="<?php echo htmlspecialchars($list->in_id, ENT_QUOTES, 'utf-8');?>" class="punt"></p>
           </div>
           </div>
           </div>  
              </li>
    <?php endforeach; ?>      
      </ul>
    </div>

<!--Ultimos platos fila -->
  <div class="sub" style="margin-top: 0px;">
     <div class="content-etiqueta-home">
        <p>Ultimos Platos</p>
      </div>
   </div>
  <div class="recomendados-platos tercera-categ">
 <ul>
  <?php 
  foreach ($this->listault  as $list) : ?>   
        <li>
        <div class="plato_r">
               <input type="hidden" value="<?php echo htmlspecialchars($list->in_id, ENT_QUOTES, 'utf-8');?>">
               <input type="hidden" name="pun" data-id="<?php echo htmlspecialchars($list->in_id, ENT_QUOTES, 'utf-8'); ?>"value="<?php echo htmlspecialchars($list->Puntaje, ENT_QUOTES, 'utf-8');?>">
                   <div class="mosaic-block cover">
                   <div class="mosaic-overlay"><span><?php echo htmlspecialchars($list->va_nombre, ENT_QUOTES, 'utf-8');?></span>
                   <img src="/imagenes/<?php echo htmlspecialchars($list->va_imagen, ENT_QUOTES, 'utf-8'); ?>" class="img-plato"><img src="img/mas.png" alt="" class="mas">
                   </div>
                   <a href="/platos/index/verplatos?id=<?php echo $list->in_id;?>" target="_blank" class="mosaic-backdrop">

                     <div class="details">
                         <h4><?php echo htmlspecialchars($list->va_nombre, ENT_QUOTES, 'utf-8'); ?></h4>
                         <p style="font-weight: bold;font-size: 0.9em;">Ingredientes</p>
                         <p style="font-size:0.9em;"><?php echo htmlspecialchars($list->tx_descripcion, ENT_QUOTES, 'utf-8'); ?> </p>
                     </div>
                    </a>
                </div>
          <div class="foo">
            <p class="nom_res"><?php echo htmlspecialchars($list->restaurant_nombre, ENT_QUOTES, 'utf-8');?></p>
            <div class="pt">
               <p class="pre"><?php echo 'S/. '.  htmlspecialchars($list->va_precio, ENT_QUOTES, 'utf-8'); ?></p>
               <p class="com"><?php echo $list->NumeroComentarios ?> <i class="icon-comment"></i></p>
            <p id="<?php echo htmlspecialchars($list->in_id, ENT_QUOTES, 'utf-8');?>" class="punt"></p>
            </div>
          </div>
        </div>
      </li>     
        <?php endforeach; ?>
      </ul>
    </div>

</div>
<script>
  $(document).ready(function(){
      var puntaje = function(item,p){
     $(item).raty({ 
                    readOnly: true,
                    score: p, 
                    starOff: '/img/t2.png',
                    starOn : '/img/t1.png'                        
      });
   }
     $(".plato_r").find(':input').each(function() {
         var elemento= this;
         var e = $(this).attr("data-id");
         var ptaje;
         var idptje;
         if( elemento.name=="pun"){
        idptje = e;
         ptaje= elemento.value;
        puntaje("#" + idptje ,ptaje); 
         }
        });

  });
</script>


