 <div class="guia">
          <img src="/img/pasos.png" alt="" style="width: 100%;">
</div>   
<div class="sub">
            <span class="titulo-portada">Platos Destacados </span>
        </div>
  <?php 
  foreach ($this->lista  as $list) : ?>   
        <div class="plato_r">
   
                         <input type="hidden" value=" <?php echo htmlspecialchars($list->in_id, ENT_QUOTES, 'utf-8'); ?>">
                         <input type="hidden" value=" <?php echo htmlspecialchars($list->Puntaje, ENT_QUOTES, 'utf-8'); ?>">
                           <div class="mosaic-block cover">
                           <div class="mosaic-overlay"><span><?php echo htmlspecialchars($list->va_nombre, ENT_QUOTES, 'utf-8'); ?></span>
                           <img src="/imagenes/<?php echo htmlspecialchars($list->va_imagen, ENT_QUOTES, 'utf-8'); ?>" class="img-plato"><img src="img/mas.png" alt="" class="mas">
                           </div>
                           <a href="/platos/index/verplatos?id=<?php echo $list->in_id;?>" target="_blank" class="mosaic-backdrop">
                             <div class="details">
                                 <h4><?php echo htmlspecialchars($list->va_nombre, ENT_QUOTES, 'utf-8'); ?></h4>
                                 <p style="font-weight: bold;">Ingredientes</p>
                                 <p style="font-size:0.9em;"><?php echo htmlspecialchars($list->tx_descripcion, ENT_QUOTES, 'utf-8'); ?> </p>
                             </div>
                         </a>
                             </div>
                             <div class="foo">
           <p class="nom_res"><?php echo htmlspecialchars($list->restaurant_nombre, ENT_QUOTES, 'utf-8'); ?></p>
           <div class="pt">
               <p class="pre"><?php echo 'S/. '.  htmlspecialchars($list->va_precio, ENT_QUOTES, 'utf-8'); ?></p>
               <p class="com"><?php echo $list->NumeroComentarios ?><i class="icon-comment"></i></p>
           <p id="star" class="punt"></p>
           </div>
           </div>

           </div>  
      
<?php endforeach; ?>
        <div class="sub">
            <span class="titulo-portada">Platos Recomendados </span>
        </div>
  <?php 
  foreach ($this->listaval  as $list) : ?>   
        <div class="plato_r">
   
                         <input type="hidden" value="<?php echo htmlspecialchars($list->in_id, ENT_QUOTES, 'utf-8');?>">
                       <input type="hidden" value="<?php echo htmlspecialchars($list->Puntaje, ENT_QUOTES, 'utf-8');?>">
                           <div class="mosaic-block cover">
                           <div class="mosaic-overlay"><span><?php echo htmlspecialchars($list->va_nombre, ENT_QUOTES, 'utf-8');?></span>
                           <img src="/imagenes/<?php echo htmlspecialchars($list->va_imagen, ENT_QUOTES, 'utf-8'); ?>" class="img-plato"><img src="img/mas.png" alt="" class="mas">
                           </div>
                           <a href="#" target="_blank" class="mosaic-backdrop">
                             <div class="details">
                                 <h4><?php echo htmlspecialchars($list->va_nombre, ENT_QUOTES, 'utf-8'); ?></h4>
                                 <p style="font-weight: bold;font-size: 0.9em;">Ingredientes</p>
                                 <p style="font-size:0.9em;"><?php echo htmlspecialchars($list->tx_descripcion, ENT_QUOTES, 'utf-8'); ?> </p>
                             </div>
                         </a>
                             </div>
                             <div class="foo">
           <p class="nom_res"><?php echo htmlspecialchars($list->restaurant_nombre, ENT_QUOTES, 'utf-8');?></p>
           <div class="pt">
               <p class="pre"><?php echo 'S/. '.  htmlspecialchars($list->va_precio, ENT_QUOTES, 'utf-8'); ?></p>
               <p class="com"><?php echo $list->NumeroComentarios ?><i class="icon-comment"></i></p>
           <p id="star" class="punt"></p>
           </div>
           </div>

           </div>  
      
<?php endforeach; ?>
