<?php
 $this->headTitle('Solicitar:');
?>
<script src="<?php echo $this->host('ruta')?>/js/vendor/jquery.validate.min.js?v<?php echo $this->host('version')?>"></script>
<div class="content-left">
	<div class="descrip-product">
        
            <?php if($_GET['id']=='') {?>
		<div class="contenido-static">
			<h2>Solicite registrar un plato</h2>
			<p>Si conoces un plato que te agrada, el lugar donde lo venden y no lo encontraste en <a href="<?php echo $this->host('ruta')?>" title="Lista del sabor" atl="listadelsabor">listadelsabor.com</a>, por favor llena el siguiente formulario y nos estaremos comunicando contigo para registrarlo.</p>
	
	<?php
			$form = $this->form;
			//$form->setAttribute('action', $this->url('usuario', array('action' => 'add')));

			$form->setAttributes(array(
			    'action' => $this->url.'/solicita',
			    'method' => 'post',
			    'class' => 'form-horizontal',
                            'id'=>'application'
			));
			$form->prepare();

			echo $this->form()->openTag($form);
			echo $this->formHidden($form->get('in_id'));
			
			?>
			<h3>Sobre ti:</h3>
			<div class="control-group">
			    <label class="control-label" for="inputName">Nombre Completo<span class="red">*</span>:</label>
			    <div class="controls">
			      <?php echo $this->formRow($form->get('va_nombre_contacto'));?>
			    </div>
			</div>
			<div class="control-group">
			    <label class="control-label" for="inputEmail">Email<span class="red">*</span>:</label>
			    <div class="controls">
			      <?php echo $this->formRow($form->get('va_correo'));?>
			    </div>
			</div>
                            <div class="control-group">
			    <label class="control-label" for="inputEmail">Teléfono:</label>
			    <div class="controls">
			      <?php echo $this->formRow($form->get('va_telefono'));?>
			    </div>
			</div>
			<h3>Sobre el restaurante:</h3>
			<div class="control-group">
			    <label class="control-label" for="inpuNombre">Nombre del restaurante<span class="red">*</span>:</label>
			    <div class="controls">
			      <?php echo $this->formRow($form->get('va_nombre_restaurante'));?>
			    </div>
			</div>
                        
                        <div class="control-group ">
			    <label class="control-label" for="inputEmail">Tipo de comida :</label>
			    <div class="controls span4">
			      <?php echo $this->formRow($form->get('Ta_tipo_comida_in_id'));?>
			    </div>
			</div>
			<div class="control-group">
			    <label class="control-label" for="inputEmail">Imagen de Restaurante:</label>
			    <div class="controls">
			      <?php echo $this->formRow($form->get('va_imagen'));?>
			    </div>
			</div>
			<div class="control-group">
			    <label class="control-label" for="inputEmail">Direccion<span class="red">*</span>:</label>
			    <div class="controls">
			      <?php echo $this->formRow($form->get('va_direccion'));?>
			    </div>
			</div>
			<div class="control-group">
			    <label class="control-label" for="inputEmail">Horario de Atención:</label>
			    <div class="controls">
			      <?php echo $this->formRow($form->get('va_horario'));?>
			    </div>
			</div>
                    
			<div class="control-group">
			    <div class="controls">
			      <?php echo $this->formSubmit($form->get('submit'));?>
			    </div>
			</div>
                       
                         <?php echo $this->form()->closeTag();?> 
                        
                       
		        </div>
                      <?php } else { ?> <div class="contenido-static">
			<h2>Solicite registrar un plato</h2>
			<p>Si conoces un plato que te agrada, el lugar donde lo venden y no lo encontraste en <a href="<?php echo $this->host('ruta')?>" title="Lista del sabor" atl="listadelsabor">listadelsabor.com</a>, por favor llena el siguiente formulario y nos estaremos comunicando contigo para registrarlo.</p>
                        <br>

	<?php
			$formu = $this->formu;
			
			$formu->setAttributes(array(
			    'action' => $this->url.'/ingresarplatos',
			    'method' => 'post',
			    'class' => 'form-horizontal',
                            'id'=>'application3'
			));
			$formu->prepare();

			echo $this->form()->openTag($formu);
			echo $this->formHidden($formu->get('Ta_registro_in_id')->setValue($_GET['id']));
			
			?>
			<h3>Datos del Plato:</h3>
			<div class="control-group">
			    <label class="control-label" for="inputName">Nombre del Plato<span class="red">*</span>:</label>
			    <div class="controls">
			      <?php echo $this->formRow($formu->get('va_nombre_plato'));?>
			    </div>
			</div>
			<div class="control-group">
			    <label class="control-label" for="inputEmail">Imagen del plato<span class="red">*</span>:</label>
			    <div class="controls">
			      <?php echo $this->formRow($formu->get('va_imagen'));?>
			    </div>
			</div>
                            <div class="control-group">
			    <label class="control-label" for="inputEmail">Descripción del plato:</label>
			    <div class="controls">
			      <?php echo $this->formRow($formu->get('va_descripcion'));?>
			    </div>
			</div>
			<div class="control-group">
			    <label class="control-label" for="inpuNombre">Precio del plato<span class="red">*</span>:</label>
			    <div class="controls">
			      <?php echo $this->formRow($formu->get('va_precio'));?>
			    </div>
			</div>
			<div class="control-group">
			    <div class="controls">
			      <?php echo $this->formSubmit($formu->get('submit'));?>
			    </div>
			</div>
                       
                         <?php echo $this->form()->closeTag();?> 
                        
                       
		        </div>  <?php if($this->mensaje){ ?>
            <div class="alert alert-success"><?php echo $this->mensaje[0];?></div>
            <?php } ?><?php  }?>
			</div>
            
                       
	
	
</div>
<script type="text/javascript">

$('#submitbutton').click(function(){
	submitForm();
});
$('#submitbutton2').click(function(){
	submitFormPlato();
});

function submitForm(){ 
	var validator = $("#application").validate({ 
	rules: {
		va_nombre_contacto: {
			required: true
		}, 
		va_correo: {
			required: true,
			email: true
		}, 
		va_nombre_restaurante: {
			required: true
		},
		va_direccion: {
			required: true
		},
		va_imagen: {
			required: true
		}

	}, 
	errorElement: "em", 
	messages: { 
		va_nombre_contacto: "Ingrese su nombre completo", 
		va_correo: {
			required: "Ingrese su correo electrónico",
			email: "Ingrese un correo valido"
		}, 
		va_nombre_restaurante: "Ingrese el nombre del restaurante",
		va_direccion:{
			required: "Ingrese su dirección"
		},
		va_imagen: {
			required: "Ingrese una imagen del restaurante"
		}
	} 
	}); 
	if(validator.form()){ // validation perform 
			 
		$('form#application').submit(); 
	} 
}

function submitFormPlato(){ 
	var validator = $("#application3").validate({ 
	rules: {
		va_nombre_plato: {
			required: true
		}, 
		va_imagen: {
			required: true
		}, 
		va_precio: {
			required: true
		}

	}, 
	errorElement: "em", 
	messages: { 
		va_nombre_plato: "Ingrese nombre del plato", 
		va_imagen: {
			required: "Ingrese la imagen del plato"
		}, 
		va_precio: "Ingrese el precio del plato"
	} 
	}); 
	if(validator.form()){ // validation perform 
			 
		$('form#application3').submit(); 
	} 
}

</script>