

<div id="sa"> <?php echo $this->json ?></div>
<div id="sa"> <input id="ur" type="hidden" value='<?php echo $this->json ?>'/></div>
  <div>
        <div id='map' style="height:400px;"></div>
      </div>

 <script type="text/javascript">
   var map;
   $(document).ready(function(){

     var mcOptions = { maxZoom: 14};
     map = new GMaps({
       el: '#map',
       zoom: 12,
        lat: -12.043333,
        lng: -77.028333,
       markerClusterer: function(map) {
   return new MarkerClusterer(map,mcOptions);
 }

     });
     var url = "";
     console.log(url);
     $.getJSON( url, function(data) {
             $.each( data.response.docs, function(i, marker) {
                 map.setCenter(marker.latitud,marker.longitud );
                  console.log(marker);
               map.addMarker({
                   lat: marker.latitud,
                   lng: marker.longitud,
                   icon : {
               size : new google.maps.Size(32, 37),
               url : "/img/icomap.png"
             },
                   title: marker.restaurante ,
                   infoWindow: {
                           content: marker.name + '</br> <a href=' + 'index.html' +'>ver plato </a>'
                         }

                 });


             });

         });
   });
 </script>

