 <?php
                        header('Content-Type: text/html; charset=utf-8');
                        $limite = 9;    
                        $resultados = false;
                        $palabraBuscar = isset($_REQUEST['q']) ? $_REQUEST['q'] : false ;
                          $fd = array (  
                            'fq'=> 'en_estado:activo AND distrito:'.$_REQUEST['fq'],
                              'sort'=>'en_destaque desc',
                              ); 
                        if ($palabraBuscar)
                        { 
                          require './vendor/SolrPhpClient/Apache/Solr/Service.php';
                          $solar = new Apache_Solr_Service('192.168.1.44', 8983, '/solr/');
                          if (get_magic_quotes_gpc() == 1)
                          {
                            $palabraBuscar = stripslashes($palabraBuscar);
                          }
                          try
                          {
                            $resultados = $solar->search($palabraBuscar, 0, $limite,$fd );

                          }
                          catch (Exception $e)
                          {
                          
                                echo("<html><head><title>SEARCH EXCEPTION</title><body><pre>{$e->__toString()}</pre></body></html>");          
                          }
                        }
          
                        $limit = 3;             
                        $palabraBuscar = isset($_REQUEST['q']) ? $_REQUEST['q'] : false ;
                        $query = "($palabraBuscar) AND (en_destaque:si)";
                        $fq = array (  
                                   'sort'=>'random_' . uniqid() .' asc',
                            'fq'=> 'en_estado:activo AND distrito:'.$_REQUEST['fq'],
                            'wt'=>'json');                                              
                        $results = false;
                        if ($query)
                        { 
                          require './vendor/SolrPhpClient/Apache/Solr/Service.php';
                          $solr = new Apache_Solr_Service('192.168.1.44', 8983, '/solr/');
                          if (get_magic_quotes_gpc() == 1)
                          {
                            $query = stripslashes($query);
                          }
                          try
                          {
                            $results = $solr->search($query, 0, $limit, $fq  );

                          }
                          catch (Exception $e)
                          {
                          
                                echo("<html><head><title>SEARCH EXCEPTION</title><body><pre>{$e->__toString()}</pre></body></html>");          
                          }
                        }

                        ?>

     <form  accept-charset="utf-8" method="get" class="form-horizontal" id="bubi" autocomplete="on" >
                             
                 <SELECT name="fq" id="fq" class="span2">
                <OPTION value="">seleccione:</OPTION>
                   <?php  foreach ($this->distritos as $distritos) : ?>
                  <OPTION   value="<?php echo $distritos['ch_distrito']; ?>"><?php echo $distritos['ch_distrito']; ?></OPTION>
                  <?php endforeach; ?>
                 </SELECT>
               
                <input id="q" name="q" type="text" placeholder="Ejm: Ceviche, tallarines" value=""/>
                 <button class="verlistado" value="listar" type="submit" ></button>                       
                <a style="margin-left: 10px;text-decoration: underline;"  href="<?php echo $this->basePath(); ?>/application/index/mapa?distrito=<?php echo $_GET['fq']; ?>&plato=<?php echo ($_GET['q']); ?>" >POR MAPA </a>
                   

<?php    
echo $this->hola;
          ?> 
<?php    
   require './vendor/SolrPhpClient/Apache/Solr/Service.php';                     
 foreach ($this->mapa->response->docs as $doc)
                          {
          ?> 
                          <div class="plato_r">
                         <input type="hidden" value="<?php echo htmlspecialchars($doc->id, ENT_QUOTES, 'utf-8'); ?>">
                       <input type="hidden" name="pun" data-id="<?php echo htmlspecialchars($doc->id, ENT_QUOTES, 'utf-8'); ?>"value="<?php echo htmlspecialchars($doc->puntuacion, ENT_QUOTES, 'utf-8');?>">
                           <div class="mosaic-block cover">
                           <div class="mosaic-overlay"><span><?php echo htmlspecialchars($doc->name, ENT_QUOTES, 'utf-8'); ?></span>
                           <img src="/imagenes/<?php echo htmlspecialchars($doc->va_imagen, ENT_QUOTES, 'utf-8'); ?>" class="img-plato"><img src="/img/mas.png" alt="" class="mas">
                           </div>
                           <a href="/platos/index/verplatos?id=<?php echo htmlspecialchars($doc->id, ENT_QUOTES, 'utf-8'); ?>" target="_blank" class="mosaic-backdrop">
                             <div class="details">
                                 <h4><?php echo htmlspecialchars($doc->name, ENT_QUOTES, 'utf-8'); ?></h4>
                                 <p style="font-weight: bold;font-size: 0.9em;">Ingredientes</p>
                                 <p style="font-size:0.9em;"><?php echo htmlspecialchars($doc->tx_descripcion, ENT_QUOTES, 'utf-8'); ?> </p>
                             </div>
                         </a>
                             </div>
                      <div class="foo">
           <p class="nom_res"><?php echo htmlspecialchars($doc->restaurante, ENT_QUOTES, 'utf-8'); ?></p>

           <div class="pt">       
           <p class="com"><?php echo htmlspecialchars($doc->comentarios, ENT_QUOTES, 'utf-8'); ?> <i class="icon-comment"></i></p>
           <p id="<?php echo htmlspecialchars($doc->id, ENT_QUOTES, 'utf-8'); ?>" class="punt"></p>        
                </div>

             </div> 
             </div>
                      <?php
                          }
             ?>  <div>
        <div id='map' style="height:400px;"></div>
      </div>
 <script type="text/javascript">
   var map;
   $(document).ready(function(){

     var mcOptions = { maxZoom: 14};
     map = new GMaps({
       el: '#map',
       zoom: 12,
        lat: -12.043333,
        lng: -77.028333,
       markerClusterer: function(map) {
   return new MarkerClusterer(map,mcOptions);
 }

     });

     
   });
 </script>