<?php
	$title = 'Solicitar';
	$this->headTitle($title);
?>
<div class="content-left">
	<div class="descrip-product">
		<div class="contenido-static">
			<h2>Solicitar publicación</h2>
			<?php
			$form = $this->form;
			//$form->setAttribute('action', $this->url('usuario', array('action' => 'add')));

			$form->setAttributes(array(
			    'action' => $this->url.'/usuario/index/agregarusuario',
			    'method' => 'post'
			));
			$form->prepare();

			echo $this->form()->openTag($form);
			echo $this->formHidden($form->get('in_id'));

			?>
			<div class="control-group"><?php echo $this->formRow($form->get('nombre_complet'));?></div><?php
			?><div class="control-group"><?php echo $this->formRow($form->get('email'));?></div ><?php
			?><div class="control-group"><?php echo $this->formRow($form->get('nombre_plato'));?></div><?php
			?><div class="control-group"><?php echo $this->formRow($form->get('descripcion'));?></div><?php
			?><div class="control-group"><?php echo $this->formRow($form->get('nombre_restaurant'));?></div><?php
			?><div class="control-group"><?php echo $this->formRow($form->get('telefono'));?></div><?php
			?><div class="control-group"><?php echo $this->formSubmit($form->get('submit'));?></div><?php
			echo $this->form()->closeTag(); ?>
		</div>
	</div>
	
</div>
