                     <?php
                        header('Content-Type: text/html; charset=utf-8');
                        $limite = 9;    
                        $resultados = false;
                         $palabraBuscar = isset($_REQUEST['q']) ? $_REQUEST['q'] : false ;
                          $fd = array (  
                            'fq'=>'en_estado:activo'); 
                        if ($palabraBuscar)
                        { 
                          require './vendor/SolrPhpClient/Apache/Solr/Service.php';
                          $solar = new Apache_Solr_Service('192.168.1.44', 8983, '/solr/');
                          if (get_magic_quotes_gpc() == 1)
                          {
                            $palabraBuscar = stripslashes($palabraBuscar);
                          }
                          try
                          {
                            $resultados = $solar->search($palabraBuscar, 0, $limite,$fd );

                          }
                          catch (Exception $e)
                          {
                          
                                echo("<html><head><title>SEARCH EXCEPTION</title><body><pre>{$e->__toString()}</pre></body></html>");          
                          }
                        }
          
                        $limit = 3;             
                        $palabraBuscar = isset($_REQUEST['q']) ? $_REQUEST['q'] : false ;
                        $query = "($palabraBuscar) AND (en_destaque:si)";
                        $fq = array (  
                                   'sort'=>'random_' . uniqid() .' asc',
                            'fq'=>'en_estado:activo');                                              
                        $results = false;
                        if ($query)
                        { 
                          require './vendor/SolrPhpClient/Apache/Solr/Service.php';
                          $solr = new Apache_Solr_Service('192.168.1.44', 8983, '/solr/');
                          if (get_magic_quotes_gpc() == 1)
                          {
                            $query = stripslashes($query);
                          }
                          try
                          {
                            $results = $solr->search($query, 0, $limit, $fq  );

                          }
                          catch (Exception $e)
                          {
                          
                                echo("<html><head><title>SEARCH EXCEPTION</title><body><pre>{$e->__toString()}</pre></body></html>");          
                          }
                        }

                        ?>

                        <form  accept-charset="utf-8" method="get" class="form-horizontal" id="bubi" autocomplete="on" action='<?php echo $this->basePath(); ?>/application/index/detalleubicacion'>

                         <SELECT name="fq" id="fq" >
                        <OPTION value=""></OPTION>
                           <?php  foreach ($this->distritos as $distritos) : ?>
                          <OPTION   value="<?php echo $distritos['ch_distrito']; ?>"><?php echo $distritos['ch_distrito']; ?></OPTION>
                         <?php endforeach; ?>

                         </SELECT>  
                            <input id="q" name="q" type="text" placeholder="Ejm: Ceviche, tallarines" value=""/>
                       <button class="verlistado" value="listar" type="submit" >POR LISTAR</button>                       
                       <a  href="<?php echo $this->basePath(); ?>/application/index/mapa?distrito=<?php echo $distritos['ch_distrito']; ?>&plato=<?php echo ($_REQUEST['q']); ?>" >POR MAPA </a>

                                   

<!--                            <?php
                            if ($results)
                            {
                              $total = (int) $results->response->numFound;
                              $start = min(1, $total);
                              $end = min($limit, $total);
                            ?> -->
                   
                           
                         </form> 
<div class="sub" style="margin-top: 10px;">
            <span class="titulo-portada" style="padding-right: 45px;">Destacados <?php echo $_REQUEST['q']; ?> </span>
        </div>
      <div class="contenido-bus">
 <?php 
                foreach ($results->response->docs as $doc)
                          {
          ?> 
                          <div class="plato_r">
                         <input type="hidden" value="<?php echo htmlspecialchars($doc->id, ENT_QUOTES, 'utf-8'); ?>">
                       <input type="hidden" name="pun" data-id="<?php echo htmlspecialchars($doc->id, ENT_QUOTES, 'utf-8'); ?>"value="<?php echo htmlspecialchars($doc->puntuacion, ENT_QUOTES, 'utf-8');?>">
                           <div class="mosaic-block cover">
                           <div class="mosaic-overlay"><span><?php echo htmlspecialchars($doc->name, ENT_QUOTES, 'utf-8'); ?></span>
                           <img src="/imagenes/<?php echo htmlspecialchars($doc->va_imagen, ENT_QUOTES, 'utf-8'); ?>" class="img-plato"><img src="/img/mas.png" alt="" class="mas">
                           </div>
                           <a href="/platos/index/verplatos?id=<?php echo htmlspecialchars($doc->id, ENT_QUOTES, 'utf-8'); ?>" target="_blank" class="mosaic-backdrop">
                             <div class="details">
                                 <h4><?php echo htmlspecialchars($doc->name, ENT_QUOTES, 'utf-8'); ?></h4>
                                 <p style="font-weight: bold;font-size: 0.9em;">Ingredientes</p>
                                 <p style="font-size:0.9em;"><?php echo htmlspecialchars($doc->tx_descripcion, ENT_QUOTES, 'utf-8'); ?> </p>
                             </div>
                         </a>
                             </div>
                      <div class="foo">
           <p class="nom_res"><?php echo htmlspecialchars($doc->restaurante, ENT_QUOTES, 'utf-8'); ?></p>

           <div class="pt">       
           <p class="com"><?php echo htmlspecialchars($doc->comentarios, ENT_QUOTES, 'utf-8'); ?> <i class="icon-comment"></i></p>
           <p id="<?php echo htmlspecialchars($doc->id, ENT_QUOTES, 'utf-8'); ?>" class="punt"></p>        
                </div>

             </div> 
             </div>


                      <?php
                          }
                      ?>   
                
                      <?php
                      }  else 
                           {
                         // echo 'no existen resultados para su busqueda';   
                           }
                      ?>  
                            
                        </div>
               
                            
        <div class="sub" style="margin-top: 2em;margin-bottom: 2em;">
            <span class="titulo-portada" style="padding-right: 45px;">Resultados <?php echo $_REQUEST['q']; ?> </span>
        </div>                    
                                              
                  <?php 
                foreach ($resultados->response->docs as $doc)
                          {
                      ?> 

                       <div class="plato_h">
                         <input type="hidden" name="pun" data-id="<?php echo htmlspecialchars($doc->id, ENT_QUOTES, 'utf-8'); ?>"value="<?php echo htmlspecialchars($doc->puntuacion, ENT_QUOTES, 'utf-8');?>">
                         <div class="lateral" >
                          <img src="/img/mas.png" alt="" class="mas-det">
                          <a href="/platos/index/verplatos?id=<?php echo htmlspecialchars($doc->id, ENT_QUOTES, 'utf-8'); ?>" target="_blank" >
                               <img src="/imagenes/<?php echo htmlspecialchars($doc->va_imagen, ENT_QUOTES, 'utf-8'); ?>" style="width: 144px;height: 120px;">
                          </a>
                          </div>
                          <div class="detalle-restaurante">
                          <div class="detalle-nombre"><p class="nombre_r"><?php echo htmlspecialchars($doc->restaurante, ENT_QUOTES, 'utf-8'); ?></p> <p id="<?php echo htmlspecialchars($doc->id, ENT_QUOTES, 'utf-8'); ?>" style="margin: 0px;width: 118px !important;display:inline-block;" ></p></div>
                              <p class="nom_plato"><?php echo htmlspecialchars($doc->name, ENT_QUOTES, 'utf-8'); ?></p>
                              <p style="margin-left:10px;"><?php echo htmlspecialchars($doc->tx_descripcion, ENT_QUOTES, 'utf-8'); ?></p>
                              <p class="com-pla"><?php echo htmlspecialchars($doc->comentarios, ENT_QUOTES, 'utf-8'); ?><i class="icon-comment"></i> Comentarios</p>

                          </div>

                          </div>
                         
                       
                      <?php
                          }
                      ?>   
                
<script>
  $(document).ready(function(){
      var puntaje = function(item,p){
     $(item).raty({ 
                    readOnly: true,
                    score: p, 
                    starOff: '/img/t2.png',
                    starOn : '/img/t1.png'                        
      });
   }
     $(".plato_r").find(':input').each(function() {
         var elemento= this;
         var e = $(this).attr("data-id");
         var ptaje;
         var idptje;
         if( elemento.name=="pun"){
        idptje = e;
         ptaje= elemento.value;
        puntaje("#" + idptje ,ptaje); 
         }
        });
         $(".plato_h").find(':input').each(function() {
         var elemento= this;
         var e = $(this).attr("data-id");
         var ptaje;
         var idptje;
         if( elemento.name=="pun"){
        idptje = e;
         ptaje= elemento.value;
        puntaje("#" + idptje ,ptaje); 
         }
        });

  });
</script>
