<?php  $this->images;?>
<?php
$form = $this->form;
//$form->setAttribute('action', $this->url('usuario', array('action' => 'add')));

$form->setAttributes(array(
    'action' => $this->url.'/application/index/detalleubicacion',
    'method' => 'get'
));
$form->prepare();

echo $this->form()->openTag($form);
?>
<?php
echo $this->formHidden($form->get('in_id'));
?><?php echo $this->formRow($form->get('distrito'));?><?php
?><?php echo $this->formRow($form->get('q'));?><?php


?><?php echo $this->formSubmit($form->get('submit'));?><?php
?><a style="margin-left: 10px;" class="disabled" id="buscarmap" disabled>Ver Mapa </a><?php
echo $this->form()->closeTag(); ?>



                    
<div id="esconder">
<div class="sub" style="margin-top: 10px;background: url(/img/img-resultados.png);width: 41%;padding: 0.9em 0px;">
            <span  style="padding-left: 10px;color:white;font-weight: bold;">Destacados <?php echo $this->nombre; ?> </span>
        </div>
      <div class="contenido-bus">
 <?php 
                foreach ($this->hola as $doc)
                          {
          ?> 
                          <div class="plato_r">
                         <input type="hidden" value="<?php echo htmlspecialchars($doc->id, ENT_QUOTES, 'utf-8'); ?>">
                       <input type="hidden" name="pun" data-id="<?php echo htmlspecialchars($doc->id, ENT_QUOTES, 'utf-8'); ?>"value="<?php echo htmlspecialchars($doc->puntuacion, ENT_QUOTES, 'utf-8');?>">
                           <div class="mosaic-block cover">
                           <div class="mosaic-overlay"><span><?php echo htmlspecialchars($doc->name, ENT_QUOTES, 'utf-8'); ?></span>
                           <img src="/imagenes/<?php echo htmlspecialchars($doc->va_imagen, ENT_QUOTES, 'utf-8'); ?>" class="img-plato"><img src="/img/mas.png" alt="" class="mas">
                           </div>
                           <a href="/platos/index/verplatos?id=<?php echo htmlspecialchars($doc->id, ENT_QUOTES, 'utf-8'); ?>&q=<?php echo $this->nombre; ?>" target="_blank" class="mosaic-backdrop">
                             <div class="details">
                                 <h4><?php echo htmlspecialchars($doc->name, ENT_QUOTES, 'utf-8'); ?></h4>
                                 <p style="font-weight: bold;font-size: 0.9em;">Ingredientes</p>
                                 <p style="font-size:0.9em;"><?php echo htmlspecialchars($doc->tx_descripcion, ENT_QUOTES, 'utf-8'); ?> </p>
                             </div>
                         </a>
                             </div>
                      <div class="foo">
           <p class="nom_res"><?php echo htmlspecialchars($doc->restaurante, ENT_QUOTES, 'utf-8'); ?></p>

           <div class="pt">       
           <p class="com"><?php echo htmlspecialchars($doc->comentarios, ENT_QUOTES, 'utf-8'); ?> <i class="icon-comment"></i></p>
           <p id="<?php echo htmlspecialchars($doc->id, ENT_QUOTES, 'utf-8'); ?>" class="punt"></p>        
                </div>

             </div> 
             </div>


                      <?php
                          }
                        ?>   
                
                  
                            
                        </div>
               
                            
        <div class="sub" style="margin-top: 1em;margin-bottom: 2em;background: url(/img/img-resultados.png);width: 41%;padding: 0.9em 0px;">
            <span style="padding-left: 10px;color:white;font-weight: bold;">Resultados <?php echo $_REQUEST['q']; ?> </span>
        </div>                    
                                              
                  <?php 
                foreach ($this->holas as $doc)
                          {
                      ?> 

                       <div class="plato_h">
                         <input type="hidden" name="pun" data-id="<?php echo htmlspecialchars($doc->id, ENT_QUOTES, 'utf-8'); ?>"value="<?php echo htmlspecialchars($doc->puntuacion, ENT_QUOTES, 'utf-8');?>">
                         <div class="lateral" >
                          <img src="/img/mas.png" alt="" class="mas-det">
                          <a href="/platos/index/verplatos?id=<?php echo htmlspecialchars($doc->id, ENT_QUOTES, 'utf-8'); ?>" target="_blank" >
                               <img src="/imagenes/<?php echo htmlspecialchars($doc->va_imagen, ENT_QUOTES, 'utf-8'); ?>" style="width: 144px;height: 120px;">
                          </a>
                          </div>
                          <div class="detalle-restaurante">
                          <div class="detalle-nombre"><p class="nombre_r"><?php echo htmlspecialchars($doc->restaurante, ENT_QUOTES, 'utf-8'); ?></p> <p id="<?php echo htmlspecialchars($doc->id, ENT_QUOTES, 'utf-8'); ?>" style="margin: 0px;width: 118px !important;display:inline-block;" ></p></div>
                              <p class="nom_plato"><?php echo htmlspecialchars($doc->name, ENT_QUOTES, 'utf-8'); ?></p>
                              <p style="margin-left:10px;"><?php echo htmlspecialchars($doc->tx_descripcion, ENT_QUOTES, 'utf-8'); ?></p>
                              <p class="com-pla"><?php echo htmlspecialchars($doc->comentarios, ENT_QUOTES, 'utf-8'); ?><i class="icon-comment"></i> Comentarios</p>

                          </div>

                          </div>
                         
                       
                      <?php
                          }
                      ?>   
       </div>         

  <div id="mapa-buscador">
<!--        <div id='map' style="height:800px;"></div>-->
 </div>



 <script type="text/javascript">
   var map;
   $(document).ready(function(){
$('#buscarmap').hide();
 $('#bubi #q').keyup(function () {
      if(($(this).val() != "") &&  ($('#bubi #fq').val() != "" )){
      $('#buscarmap').removeClass("disabled").addClass('map');
      $('#buscarmap').attr("href","#");
      $('#buscarmap' ).removeAttr('disabled');
       $('#buscarmap').fadeIn();
      }   }).keyup();

  var puntaje = function(item,p){
     $(item).raty({ 
                    readOnly: true,
                    score: p, 
                    starOff: '/img/t2.png',
                    starOn : '/img/t1.png'                        
      });
   }
     $(".plato_r").find(':input').each(function() {
         var elemento= this;
         var e = $(this).attr("data-id");
         var ptaje;
         var idptje;
         if( elemento.name=="pun"){
        idptje = e;
         ptaje= elemento.value;
        puntaje("#" + idptje ,ptaje); 
         }
        });
         $(".plato_h").find(':input').each(function() {
         var elemento= this;
         var e = $(this).attr("data-id");
         var ptaje;
         var idptje;
         if( elemento.name=="pun"){
        idptje = e;
         ptaje= elemento.value;
        puntaje("#" + idptje ,ptaje); 
         }
        });
       

       $("#buscarmap").on("click",function(){
        $("#mapa-buscador").append("<div id='map' style='height:800px;'></div>");
         var map;
           var mcOptions = { maxZoom: 12};
             map = new GMaps({
               el: '#map',
               zoom: 14,
                lat: -12.043333,
                lng: -77.028333,
               markerClusterer: function(map) {
           return new MarkerClusterer(map,mcOptions);
         }
       });
       
     $('#esconder').css("display","none");
    
     var plato=$('#bubi #q').val();
     var dis=$('#bubi #fq').val();

     var url = "http://zf2.pe:8080/application/index/jsonmapasa?distrito=" + dis+ "&plato=" + plato;
     console.log(url);
     if ( ($('#bubi #q').val() != "") && ($('#bubi #fq').val()!="") ){
     $.getJSON( url, function(data) {
             $.each( data.response.docs, function(i, marker) {
                 map.setCenter(marker.latitud,marker.longitud );
                  console.log(marker);
               map.addMarker({
                   lat: marker.latitud,
                   lng: marker.longitud,
                   icon : {
               size : new google.maps.Size(32, 37),
               url : "/img/icomap.png"
             },
                   title: marker.restaurante ,
                   infoWindow: {
                           content: marker.name + '</br> <a href=/platos/index/verplatos?id=' + marker.id +'&q=' + plato +'>ver plato </a>'
                         }

                 });


             });

         });
   }
        
     });
     
   });
 </script>